//! Guest crate scaffold templates for `upeg plugin new`.
//!
//! Pure string generation — no filesystem I/O (`app::plugin_command`
//! owns writing these to disk). Both `Cargo.toml` and `src/lib.rs` are
//! single raw-string templates with `{{placeholder}}` tokens substituted
//! by [`substitute`], so there is exactly one place that assembles
//! template text instead of scattered `format!` fragments spread across
//! the scaffolding code. Mirrors `examples/plugins/greet`'s shape.

use std::path::Path;

/// Canonical UPeg repo URL used for the default git-dependency scaffold.
/// Single definition — every git dependency line renders from this.
const UPEG_REPO_URL: &str = "https://github.com/5pecia1/UPeg";

/// Generated file contents for a scaffolded guest crate.
pub(crate) struct ScaffoldFiles {
    pub(crate) cargo_toml: String,
    pub(crate) lib_rs: String,
}

/// Render the scaffold for a plugin named `name` (already validated by
/// [`super::name::validate_plugin_name`]). When `local_upeg_repo` is
/// `Some`, `Cargo.toml` depends on `upeg-plugin-api`/`upeg-plugin-macros`
/// via `path = "..."` against that checkout instead of `git = "..."` —
/// for in-repo development against unreleased macro/runtime changes.
pub(crate) fn render(name: &str, local_upeg_repo: Option<&Path>) -> ScaffoldFiles {
    let (plugin_api_dep, plugin_macros_dep) = dependency_toml(local_upeg_repo);
    ScaffoldFiles {
        cargo_toml: substitute(
            CARGO_TOML_TEMPLATE,
            &[
                ("name", name),
                ("plugin_api_dep", &plugin_api_dep),
                ("plugin_macros_dep", &plugin_macros_dep),
            ],
        ),
        lib_rs: substitute(LIB_RS_TEMPLATE, &[("name", name)]),
    }
}

fn dependency_toml(local_upeg_repo: Option<&Path>) -> (String, String) {
    match local_upeg_repo {
        Some(repo) => {
            let repo = repo.display();
            (
                format!("{{ path = \"{repo}/upeg-plugin-api\" }}"),
                format!("{{ path = \"{repo}/upeg-plugin-macros\" }}"),
            )
        }
        None => (
            format!("{{ git = \"{UPEG_REPO_URL}\" }}"),
            format!("{{ git = \"{UPEG_REPO_URL}\" }}"),
        ),
    }
}

/// Substitute every `{{key}}` placeholder in `template` with its paired
/// value. Deliberately a plain literal-string replace, not a templating
/// engine — the placeholder set is small and closed.
fn substitute(template: &str, pairs: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (key, value) in pairs {
        let placeholder = ["{{", key, "}}"].concat();
        out = out.replace(&placeholder, value);
    }
    out
}

const CARGO_TOML_TEMPLATE: &str = r#"# upeg WASM plugin scaffold — generated by `upeg plugin new`.
#
# Two ways to depend on upeg-plugin-api / upeg-plugin-macros:
#   - git (default, used below): pins straight to the UPeg repo, works
#     from anywhere.
#   - path (`upeg plugin new {{name}} --local <upeg-repo-path>`): points
#     at a local UPeg checkout instead, for developing against
#     unreleased macro/runtime changes from inside the UPeg repo itself.
#
# Build:
#
#   cd {{name}}
#   cargo build --target wasm32-unknown-unknown --release
#
# Install:
#
#   upeg plugin install target/wasm32-unknown-unknown/release/{{name}}.wasm

[workspace]

[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1"
serde_json = "1"
upeg-plugin-api = {{plugin_api_dep}}
upeg-plugin-macros = {{plugin_macros_dep}}

[profile.release]
lto = true
opt-level = "s"
"#;

const LIB_RS_TEMPLATE: &str = r#"//! `{{name}}` — a upeg WASM plugin scaffolded by `upeg plugin new`.
//!
//! Exports one starter tool `{{name}}.hello` that takes `{"name": "<str>"}`
//! and returns `"Hello, <name>!"`. Add more `#[tool]`-annotated functions
//! and list each one in `upeg_plugin!`'s `tools:` array.

use upeg_plugin_macros::{tool, upeg_plugin};

/// Greet a person by name.
#[tool(
    id = "{{name}}.hello",
    toolkit = "{{name}}",
    pegboard_units = U1,
    inputs = [ required name: String = "Person to greet" ],
)]
pub fn {{name}}_hello(name: &str) -> String {
    format!("Hello, {name}!")
}

upeg_plugin! {
    toolkit: "{{name}}",
    tools: [{{name}}_hello],
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn name_is_substituted_at_every_token_site() {
        let files = render("greet2", None);
        assert!(files.cargo_toml.contains("name = \"greet2\""));
        assert!(!files.cargo_toml.contains("{{name}}"));
        assert!(files.lib_rs.contains("id = \"greet2.hello\""));
        assert!(files.lib_rs.contains("toolkit = \"greet2\""));
        assert!(
            files
                .lib_rs
                .contains("pub fn greet2_hello(name: &str) -> String {")
        );
        assert!(files.lib_rs.contains("tools: [greet2_hello],"));
        assert!(!files.lib_rs.contains("{{name}}"));
    }

    #[test]
    fn default_scaffold_uses_git_dependencies() {
        let files = render("greet2", None);
        assert!(files.cargo_toml.contains(&format!(
            "upeg-plugin-api = {{ git = \"{UPEG_REPO_URL}\" }}"
        )));
        assert!(files.cargo_toml.contains(&format!(
            "upeg-plugin-macros = {{ git = \"{UPEG_REPO_URL}\" }}"
        )));
    }

    #[test]
    fn local_flag_uses_path_dependencies() {
        let files = render("greet2", Some(Path::new("/workspaces/UPeg")));
        assert!(
            files
                .cargo_toml
                .contains("upeg-plugin-api = { path = \"/workspaces/UPeg/upeg-plugin-api\" }")
        );
        assert!(
            files.cargo_toml.contains(
                "upeg-plugin-macros = { path = \"/workspaces/UPeg/upeg-plugin-macros\" }"
            )
        );
        assert!(!files.cargo_toml.contains("git ="));
    }
}
