//! flutter_rust_bridge cdylib for upeg's Flutter frontend.
//!
//! Phase 2 ships the boot/lifecycle surface only. Phase 4 fills in
//! tools/pegboard/palette/embed/services/tweaks/deep_link/events
//! per the design spec §4.

#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::get_unwrap,
        clippy::tests_outside_test_module,
        clippy::print_stdout,
        clippy::unreachable,
        clippy::string_add,
        clippy::manual_let_else,
        reason = "tests use unwrap/expect/panic idiomatically and need not satisfy production restriction lints"
    )
)]

pub mod api;
pub mod platform;

// The codegen-emitted module contains `#[unsafe(no_mangle)] extern "C"`
// shims, wildcard imports, `unwrap()` on `Option`, `unreachable!()` arms,
// and other clippy::pedantic/restriction patterns that are inherent to
// FRB's FFI dispatch table. Allow them only inside the generated subtree;
// the hand-written `api` modules remain held to the full workspace lint
// strictness. Codegen overwrites `frb_generated.rs` on every run so the
// allow list lives on the `mod` declaration, not inside the file.
#[allow(
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    reason = "generated by flutter_rust_bridge_codegen"
)]
mod frb_generated;
