// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_backup`, `current_backup`, `current_boards`, `current_layouts_owned`, `validated_boards`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Snapshot every persisted piece of desktop state as pretty-printed JSON.
///
/// Reads through `upeg_pegboard_ui::platform::storage` so the snapshot
/// matches whatever is currently written to disk — there is no in-memory
/// state machine to race against on the FRB side.
String exportBackup() => RustLib.instance.api.crateApiBackupExportBackup();

/// Validate + apply an imported backup. Returns counts on success;
/// [`FrbError::Validation`] when the JSON shape, version, or any
/// required field disagrees with the current schema; [`FrbError::Io`]
/// when the parse succeeded but persisting to storage failed.
BackupImportReportDto importBackup({required String json}) =>
    RustLib.instance.api.crateApiBackupImportBackup(json: json);

/// Counts surfaced after a successful import. The Flutter side renders
/// this in the post-import toast so the user sees how much was restored.
class BackupImportReportDto {
  final int boardCount;
  final int layoutCount;
  final int memoCount;

  const BackupImportReportDto({
    required this.boardCount,
    required this.layoutCount,
    required this.memoCount,
  });

  @override
  int get hashCode =>
      boardCount.hashCode ^ layoutCount.hashCode ^ memoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupImportReportDto &&
          runtimeType == other.runtimeType &&
          boardCount == other.boardCount &&
          layoutCount == other.layoutCount &&
          memoCount == other.memoCount;
}
