// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `readiness_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Read guidance without implying the browser has access to native project files.
Future<BoardDetailsDto> loadBoardDetails({required String boardKey}) => RustLib
    .instance
    .api
    .crateApiBoardDetailsLoadBoardDetails(boardKey: boardKey);

/// Save personal guidance through the shared store; project manifests own theirs.
Future<void> saveBoardGuidance({
  required String boardKey,
  required String description,
  required String instructions,
}) => RustLib.instance.api.crateApiBoardDetailsSaveBoardGuidance(
  boardKey: boardKey,
  description: description,
  instructions: instructions,
);

/// Preview the same scoped tools and defaults the agent receives on connection.
/// The directory is fixed to the current process so source discovery agrees.
Future<BoardConnectionPreviewDto> previewBoardConnection({
  required String boardKey,
}) => RustLib.instance.api.crateApiBoardDetailsPreviewBoardConnection(
  boardKey: boardKey,
);

class BoardConnectionPreviewDto {
  final String boardKey;
  final String executionDirectory;
  final String? projectManifestPath;
  final List<BoardConnectionToolDto> tools;
  final String configJson;
  final BoardToolReadinessDto readiness;
  final List<String> readinessReasons;

  const BoardConnectionPreviewDto({
    required this.boardKey,
    required this.executionDirectory,
    this.projectManifestPath,
    required this.tools,
    required this.configJson,
    required this.readiness,
    required this.readinessReasons,
  });

  @override
  int get hashCode =>
      boardKey.hashCode ^
      executionDirectory.hashCode ^
      projectManifestPath.hashCode ^
      tools.hashCode ^
      configJson.hashCode ^
      readiness.hashCode ^
      readinessReasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoardConnectionPreviewDto &&
          runtimeType == other.runtimeType &&
          boardKey == other.boardKey &&
          executionDirectory == other.executionDirectory &&
          projectManifestPath == other.projectManifestPath &&
          tools == other.tools &&
          configJson == other.configJson &&
          readiness == other.readiness &&
          readinessReasons == other.readinessReasons;
}

class BoardConnectionToolDto {
  final String toolId;
  final String description;
  final String defaultsJson;
  final String inputSchemaJson;
  final String? executionDirectory;
  final BoardToolReadinessDto readiness;
  final List<String> readinessReasons;

  const BoardConnectionToolDto({
    required this.toolId,
    required this.description,
    required this.defaultsJson,
    required this.inputSchemaJson,
    this.executionDirectory,
    required this.readiness,
    required this.readinessReasons,
  });

  @override
  int get hashCode =>
      toolId.hashCode ^
      description.hashCode ^
      defaultsJson.hashCode ^
      inputSchemaJson.hashCode ^
      executionDirectory.hashCode ^
      readiness.hashCode ^
      readinessReasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoardConnectionToolDto &&
          runtimeType == other.runtimeType &&
          toolId == other.toolId &&
          description == other.description &&
          defaultsJson == other.defaultsJson &&
          inputSchemaJson == other.inputSchemaJson &&
          executionDirectory == other.executionDirectory &&
          readiness == other.readiness &&
          readinessReasons == other.readinessReasons;
}

class BoardDetailsDto {
  final String boardKey;
  final String title;
  final String description;
  final String instructions;
  final String? projectManifestPath;
  final String? executionDirectory;
  final bool nativeConnectionSupported;

  const BoardDetailsDto({
    required this.boardKey,
    required this.title,
    required this.description,
    required this.instructions,
    this.projectManifestPath,
    this.executionDirectory,
    required this.nativeConnectionSupported,
  });

  @override
  int get hashCode =>
      boardKey.hashCode ^
      title.hashCode ^
      description.hashCode ^
      instructions.hashCode ^
      projectManifestPath.hashCode ^
      executionDirectory.hashCode ^
      nativeConnectionSupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoardDetailsDto &&
          runtimeType == other.runtimeType &&
          boardKey == other.boardKey &&
          title == other.title &&
          description == other.description &&
          instructions == other.instructions &&
          projectManifestPath == other.projectManifestPath &&
          executionDirectory == other.executionDirectory &&
          nativeConnectionSupported == other.nativeConnectionSupported;
}

enum BoardToolReadinessDto { ready, unavailable, unchecked }
