// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'deep_link.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'boot.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `load_local_runtime_sources`, `log_runtime_source_report`, `native_host_bootstrap`, `skipped_tool_notes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HostState`, `SkippedToolNote`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// One-shot boot: acquires the OS-level instance lock + runs host
/// discovery (attach existing / embed new / no host).
///
/// The bootstrap result is forwarded to the host-state broadcaster
/// in `api/events.rs` so any subscriber attached after `init_app`
/// returns immediately receives the cached snapshot on subscribe.
///
/// Intentionally NOT `#[frb(sync)]`: native host discovery can block for
/// up to `EMBED_READY_TIMEOUT_SECS` waiting on the embedded HTTP host, and
/// runtime-source loading touches the filesystem. A sync FRB call runs on
/// the Dart UI isolate and would freeze the splash; the async surface runs
/// it on an FRB worker so the splash stays responsive.
Future<AppInitReport> initApp() => RustLib.instance.api.crateApiBootInitApp();

/// Re-read the launch intent without re-running the whole boot.
/// Returns `None` when argv carries no supported `upeg://open` argument
/// so the Dart side can distinguish "no deep link" from an explicit
/// default-board deep link.
///
/// The Dart `app.dart` calls this once after `initApp()` resolves and
/// seeds the result into `launchIntentProvider`, which the
/// `LaunchIntentApplier` observer drains on the first frame.
LaunchIntentDto? currentLaunchIntent() =>
    RustLib.instance.api.crateApiBootCurrentLaunchIntent();

/// Hand the host back to the OS: drops the instance lock so
/// `~/.upeg/desktop.lock` is removed even when the process exits via
/// a Dart-side teardown path. The embedded HTTP host thread keeps
/// running until process exit; its discovery `Drop` guard handles
/// cleanup. There is no explicit host-stop signal yet.
void shutdown() => RustLib.instance.api.crateApiBootShutdown();

/// Report returned by [`init_app`] so the Flutter side can render
/// the initial UI state in one round-trip.
///
/// `host_state` carries the bootstrap outcome (A07/A08) so the Dart
/// side can distinguish attached vs embedded vs no-host without
/// re-running discovery.
class AppInitReport {
  final DesktopLaunchDto launch;
  final HostStateDto hostState;
  final String version;

  const AppInitReport({
    required this.launch,
    required this.hostState,
    required this.version,
  });

  @override
  int get hashCode => launch.hashCode ^ hostState.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInitReport &&
          runtimeType == other.runtimeType &&
          launch == other.launch &&
          hostState == other.hostState &&
          version == other.version;
}

/// Non-opaque DTO mirror of [`DesktopLaunch`]. The source struct
/// holds `&'static str` fields (board/tool ids) which FRB cannot
/// ship as borrows; the owned-string copy crosses the wire instead.
class DesktopLaunchDto {
  final String board;
  final String? tool;
  final String? input;

  const DesktopLaunchDto({required this.board, this.tool, this.input});

  @override
  int get hashCode => board.hashCode ^ tool.hashCode ^ input.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DesktopLaunchDto &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          tool == other.tool &&
          input == other.input;
}

@freezed
sealed class FrbError with _$FrbError implements FrbException {
  const FrbError._();

  const factory FrbError.alreadyRunning({required int pid}) =
      FrbError_AlreadyRunning;
  const factory FrbError.hostUnavailable() = FrbError_HostUnavailable;
  const factory FrbError.projectManifestChanged({required String path}) =
      FrbError_ProjectManifestChanged;
  const factory FrbError.validation({
    required String field,
    required String reason,
  }) = FrbError_Validation;
  const factory FrbError.io({required String message}) = FrbError_Io;
  const factory FrbError.internal({required String message}) =
      FrbError_Internal;
}

@freezed
sealed class HostStateDto with _$HostStateDto {
  const HostStateDto._();

  const factory HostStateDto.attached({required String endpoint}) =
      HostStateDto_Attached;
  const factory HostStateDto.embedded({required String endpoint}) =
      HostStateDto_Embedded;
  const factory HostStateDto.noHost() = HostStateDto_NoHost;
}
