// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'capability.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `requires_dispatcher`, `surface_for`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Capability verdict for `tool_id` on the current runtime.
///
/// Unknown tool ids report `Supported` — there is no meta to prove a
/// missing capability, and dispatch will surface its own "not found"
/// error. Registration is ensured first so the dispatcher probe is accurate.
DispatchCapabilityDto dispatchCapabilityFor({required String toolId}) => RustLib
    .instance
    .api
    .crateApiCapabilityDispatchCapabilityFor(toolId: toolId);

@freezed
sealed class DispatchCapabilityDto with _$DispatchCapabilityDto {
  const DispatchCapabilityDto._();

  /// The tool can be dispatched in-process on the current surface/host.
  const factory DispatchCapabilityDto.supported() =
      DispatchCapabilityDto_Supported;

  /// The tool cannot run here; `reason` explains which capability is missing.
  const factory DispatchCapabilityDto.unsupported({
    required UnsupportedReasonDto reason,
  }) = DispatchCapabilityDto_Unsupported;
}

/// Dart-mirrored view of [`upeg_core::UnsupportedReason`]. Each variant maps
/// to a specific, localizable explanation on the Flutter side.
enum UnsupportedReasonDto {
  noProcessSpawn,
  noLoaderRuntime,
  noWasmHost,
  nativeOnlyTool,
}
