// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Parse a single `upeg://open?...` URL into a [`LaunchIntentDto`].
///
/// Returns `None` for any URL that doesn't begin with the `upeg://open?`
/// prefix so non-upeg deep-link schemes (e.g. `https://`) can be
/// dropped silently by the Dart listener.
LaunchIntentDto? parseLaunchIntent({required String uri}) =>
    RustLib.instance.api.crateApiDeepLinkParseLaunchIntent(uri: uri);

/// Encode a [`LaunchIntentDto`] back into a canonical
/// `upeg://open?...` URI. Empty / `None` fields are dropped per
/// `desktop_deep_link` semantics so the popup never produces
/// degenerate `&board=` pairs.
String encodeLaunchIntent({required LaunchIntentDto intent}) =>
    RustLib.instance.api.crateApiDeepLinkEncodeLaunchIntent(intent: intent);

/// Typed launch intent shared by the three intent sources (cold-boot
/// argv, second-instance `app_links` event, in-process popup encode).
///
/// `Option<String>` for board / tool / input_json — FRB v2 surfaces
/// nullable fields as `String?` on the Dart side, which the
/// `LaunchIntent` Dart class consumes directly without a sentinel.
class LaunchIntentDto {
  /// Static board key (e.g. `"dev"`). `None` ⇒ leave the
  /// currently-selected board alone.
  final String? board;

  /// Tool id (e.g. `"num.hex_to_decimal"`). `None` ⇒ no tool
  /// activation; only board switch.
  final String? tool;

  /// Pre-fill inputs for the tool, encoded as a JSON object string.
  /// `None` ⇒ activate with `"{}"`.
  final String? inputJson;

  const LaunchIntentDto({this.board, this.tool, this.inputJson});

  static Future<LaunchIntentDto> default_() =>
      RustLib.instance.api.crateApiDeepLinkLaunchIntentDtoDefault();

  @override
  int get hashCode => board.hashCode ^ tool.hashCode ^ inputJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchIntentDto &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          tool == other.tool &&
          inputJson == other.inputJson;
}
