// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `capture_dispatch_identity`, `context_string`, `details_with_identity`, `generated_run_id`, `now_ms`, `record_dispatch_diagnostic`, `record_native`, `report_to_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DispatchDiagnosticIdentity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// List retained reports, newest first. A zero limit means the store default.
List<DiagnosticSummaryDto> listDiagnostics({required int limit}) =>
    RustLib.instance.api.crateApiDiagnosticsListDiagnostics(limit: limit);

/// Load a report that a recent-failures panel selected.
DiagnosticReportDto? showDiagnostic({required String id}) =>
    RustLib.instance.api.crateApiDiagnosticsShowDiagnostic(id: id);

/// Serialize a safe support bundle preview. `debug` includes the stored
/// structured details; normal export keeps its useful summary and streams.
Future<String> exportDiagnostic({required String id, required bool debug}) =>
    RustLib.instance.api.crateApiDiagnosticsExportDiagnostic(
      id: id,
      debug: debug,
    );

/// Persist an uncaught Flutter-side failure through the same bounded,
/// redacting diagnostic store as native dispatch failures. The UI deliberately
/// sends only its error and stack text; no widget state or form values cross
/// this boundary.
void recordFlutterError({required String message, required String stack}) =>
    RustLib.instance.api.crateApiDiagnosticsRecordFlutterError(
      message: message,
      stack: stack,
    );

/// Full report for an explicit detail view or export preview.
class DiagnosticReportDto {
  final String id;
  final String runId;
  final BigInt occurredAtMs;
  final String appVersion;
  final String os;
  final String? toolId;
  final String source;
  final String? cwd;
  final String? project;
  final String errorCode;
  final String errorMessage;
  final String status;
  final String stdout;
  final String stderr;

  /// Available only from `show` and debug export; already redacted.
  final String? debugContext;

  const DiagnosticReportDto({
    required this.id,
    required this.runId,
    required this.occurredAtMs,
    required this.appVersion,
    required this.os,
    this.toolId,
    required this.source,
    this.cwd,
    this.project,
    required this.errorCode,
    required this.errorMessage,
    required this.status,
    required this.stdout,
    required this.stderr,
    this.debugContext,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      runId.hashCode ^
      occurredAtMs.hashCode ^
      appVersion.hashCode ^
      os.hashCode ^
      toolId.hashCode ^
      source.hashCode ^
      cwd.hashCode ^
      project.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode ^
      status.hashCode ^
      stdout.hashCode ^
      stderr.hashCode ^
      debugContext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticReportDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          runId == other.runId &&
          occurredAtMs == other.occurredAtMs &&
          appVersion == other.appVersion &&
          os == other.os &&
          toolId == other.toolId &&
          source == other.source &&
          cwd == other.cwd &&
          project == other.project &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage &&
          status == other.status &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          debugContext == other.debugContext;
}

/// Compact row for a recent-failures panel.
class DiagnosticSummaryDto {
  final String id;
  final String runId;
  final BigInt occurredAtMs;
  final String? toolId;
  final String source;
  final String errorCode;
  final String errorMessage;
  final String status;

  const DiagnosticSummaryDto({
    required this.id,
    required this.runId,
    required this.occurredAtMs,
    this.toolId,
    required this.source,
    required this.errorCode,
    required this.errorMessage,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      runId.hashCode ^
      occurredAtMs.hashCode ^
      toolId.hashCode ^
      source.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          runId == other.runId &&
          occurredAtMs == other.occurredAtMs &&
          toolId == other.toolId &&
          source == other.source &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage &&
          status == other.status;
}
