// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tools.dart';
part 'dispatch_stream.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `next`, `open`, `run_registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RegisteredRun`, `RunRegistration`, `RunSeq`, `SinkProgressForwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `drop`, `emit`, `eq`, `fmt`, `fmt`

/// Run the named tool and stream its output, then its result.
///
/// Same arguments as [`super::tools::dispatch_tool`] — including the
/// typed `approve` flag, which is the only way a desktop dispatch lifts
/// a Chain's approval barrier — plus a caller-minted `run_id` that
/// [`cancel_dispatch`] uses to reach this run's cancellation token.
///
/// Chunks only ever arrive from an invoker that reports progress (the
/// `External` invoker does; in-process function tools have nothing to
/// report), so a stream that carries a lone `Done` is a normal outcome,
/// not a failure. That is also the whole story on wasm32, which has no
/// External invoker at all.
Stream<DispatchStreamEventDto> dispatchToolStreamed({
  required String toolId,
  required String argsJson,
  String? boardKey,
  String? pinId,
  required bool approve,
  required String runId,
}) => RustLib.instance.api.crateApiDispatchStreamDispatchToolStreamed(
  toolId: toolId,
  argsJson: argsJson,
  boardKey: boardKey,
  pinId: pinId,
  approve: approve,
  runId: runId,
);

/// Ask the run registered under `run_id` to stop.
///
/// Returns whether a live run was found. `false` means the run already
/// settled (or never started) — the honest answer for a Cancel button
/// the user pressed a moment too late, and never an error.
///
/// Cancellation is cooperative: the token is tripped here and the
/// invoker's wait loop notices it. The run still ends by sending its
/// `Done` event, so the Dart side has exactly one completion path.
///
/// The entry stays in the registry. Removing it here would free the id
/// while the run it names is still running — a request to stop is not
/// the moment the run ended, and [`RunRegistration::drop`] is the one
/// place that knows which moment that is.
bool cancelDispatch({required String runId}) =>
    RustLib.instance.api.crateApiDispatchStreamCancelDispatch(runId: runId);

@freezed
sealed class DispatchStreamEventDto with _$DispatchStreamEventDto {
  const DispatchStreamEventDto._();

  /// One incremental slice of the running Tool's output. `stream` is
  /// [`upeg_runtime::ProgressStream::wire_name`] (`stdout` / `stderr`)
  /// — the same spelling the HTTP NDJSON and MCP log wires use, so the
  /// desktop surface introduces no second vocabulary.
  const factory DispatchStreamEventDto.chunk({
    required String stream,
    required BigInt seq,
    required String chunk,
  }) = DispatchStreamEventDto_Chunk;

  /// The dispatch settled. Always the last event on the stream.
  const factory DispatchStreamEventDto.done({
    required CanonicalToolResult result,
  }) = DispatchStreamEventDto_Done;
}
