// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'embed.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Resolve the embed URL for a tool. Returns `None` for tools without an
/// `OutputKind::EmbeddedView` field or an explicit `register_embed_url`
/// registration.
///
/// `args_json` is currently unused (no templating yet) but part of the
/// signature for forward compatibility.
EmbedResolutionDto? resolveEmbedUrl({
  required String toolId,
  required String argsJson,
}) => RustLib.instance.api.crateApiEmbedResolveEmbedUrl(
  toolId: toolId,
  argsJson: argsJson,
);

/// Open `url` in the user's default browser or browser tab.
void openInBrowser({required String url}) =>
    RustLib.instance.api.crateApiEmbedOpenInBrowser(url: url);

/// Return the persisted selector-binding rows for `tool_id`. Empty
/// vector when the tool has no bindings registered (either through the
/// static `#[tool]` macro path or the owned-string FRB write below).
List<SelectorBindingDto> selectorBindingsFor({required String toolId}) =>
    RustLib.instance.api.crateApiEmbedSelectorBindingsFor(toolId: toolId);

/// Persist `bindings` for `tool_id` so subsequent
/// [`selector_bindings_for`] calls see them. The owned-string registry
/// in `upeg-runtime::embed` exists specifically for this path —
/// the static-keyed `set_selector_bindings` requires `&'static str`
/// keys which FRB callers can't synthesise.
void setSelectorBindings({
  required String toolId,
  required List<SelectorBindingDto> bindings,
}) => RustLib.instance.api.crateApiEmbedSetSelectorBindings(
  toolId: toolId,
  bindings: bindings,
);

/// Return the runtime Controlled Embed settings for `tool_id`.
ControlledEmbedSettingsDto controlledEmbedSettingsFor({
  required String toolId,
}) => RustLib.instance.api.crateApiEmbedControlledEmbedSettingsFor(
  toolId: toolId,
);

/// Persist runtime Controlled Embed settings for `tool_id`.
void setControlledEmbedSettings({
  required String toolId,
  required ControlledEmbedSettingsDto settings,
}) => RustLib.instance.api.crateApiEmbedSetControlledEmbedSettings(
  toolId: toolId,
  settings: settings,
);

/// Build the three pipeline scripts (`write`, `trigger`, `read`) for
/// `bindings` + `inputs`. Pure function — same crate, same code path
/// as the headless `ControlledEmbedBackend` so live-WebView and
/// headless surfaces stay in lockstep.
ExecutionScriptsDto buildExecutionScripts({
  required List<SelectorBindingDto> bindings,
  required List<(String, String)> inputs,
}) => RustLib.instance.api.crateApiEmbedBuildExecutionScripts(
  bindings: bindings,
  inputs: inputs,
);

/// Build the wait script for a single Controlled Embed binding. Empty
/// string means the binding has no wait declaration.
String buildBindingWaitScript({required SelectorBindingDto binding}) =>
    RustLib.instance.api.crateApiEmbedBuildBindingWaitScript(binding: binding);

/// Role this binding plays in the Controlled Embed pipeline. Mirrors
/// [`upeg_core::BindingRole`] across the FRB boundary so Dart code can
/// `switch` exhaustively on a sealed enum instead of a stringly-typed
/// role.
enum BindingRoleDto {
  /// Write the corresponding input field value into the DOM target.
  input,

  /// Click the DOM target to fire the page's action.
  trigger,

  /// Read the DOM target after the trigger fires and surface it as
  /// an output keyed by `field`.
  output,
}

/// Wait condition for a binding: whether to wait for the element to
/// exist in the DOM or to become visible.
enum BindingWaitConditionDto { exists, visible }

/// Wait configuration for a single selector binding. `for_selector` is
/// an optional CSS selector to wait for (defaults to the binding's own
/// selector); `condition` selects exists-vs-visible semantics.
class BindingWaitDto {
  final String? forSelector;
  final BindingWaitConditionDto condition;
  final BigInt timeoutMs;
  final BigInt settleMs;
  final BindingWaitOnTimeoutDto onTimeout;

  const BindingWaitDto({
    this.forSelector,
    required this.condition,
    required this.timeoutMs,
    required this.settleMs,
    required this.onTimeout,
  });

  @override
  int get hashCode =>
      forSelector.hashCode ^
      condition.hashCode ^
      timeoutMs.hashCode ^
      settleMs.hashCode ^
      onTimeout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BindingWaitDto &&
          runtimeType == other.runtimeType &&
          forSelector == other.forSelector &&
          condition == other.condition &&
          timeoutMs == other.timeoutMs &&
          settleMs == other.settleMs &&
          onTimeout == other.onTimeout;
}

/// Behavior when a binding wait times out.
enum BindingWaitOnTimeoutDto { fail, continue_ }

/// Browser settings for a Controlled Embed tool.
class ControlledEmbedSettingsDto {
  final ControlledEmbedUserAgentDto? userAgent;
  final ControlledEmbedViewportDto? viewport;

  const ControlledEmbedSettingsDto({this.userAgent, this.viewport});

  @override
  int get hashCode => userAgent.hashCode ^ viewport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ControlledEmbedSettingsDto &&
          runtimeType == other.runtimeType &&
          userAgent == other.userAgent &&
          viewport == other.viewport;
}

/// Trigger action for the Controlled Embed Trigger binding.
enum ControlledEmbedTriggerActionDto { click, enter }

@freezed
sealed class ControlledEmbedUserAgentDto with _$ControlledEmbedUserAgentDto {
  const ControlledEmbedUserAgentDto._();

  const factory ControlledEmbedUserAgentDto.default_() =
      ControlledEmbedUserAgentDto_Default;
  const factory ControlledEmbedUserAgentDto.mobileSafari() =
      ControlledEmbedUserAgentDto_MobileSafari;
  const factory ControlledEmbedUserAgentDto.custom({required String value}) =
      ControlledEmbedUserAgentDto_Custom;
}

@freezed
sealed class ControlledEmbedViewportDto with _$ControlledEmbedViewportDto {
  const ControlledEmbedViewportDto._();

  const factory ControlledEmbedViewportDto.preset({
    required ControlledEmbedViewportPresetDto preset,
  }) = ControlledEmbedViewportDto_Preset;
  const factory ControlledEmbedViewportDto.custom({
    required int width,
    required int height,
  }) = ControlledEmbedViewportDto_Custom;
}

/// Named viewport presets for Controlled Embed sessions.
enum ControlledEmbedViewportPresetDto { mobile, tablet, desktop }

/// Dart-mirrored embed resolution. Platform routing (in-app webview vs.
/// iframe vs. external launcher) is decided by `WebViewPanel` from
/// `kIsWeb` alone; Rust just hands over the URL.
class EmbedResolutionDto {
  final String url;

  const EmbedResolutionDto({required this.url});

  @override
  int get hashCode => url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedResolutionDto &&
          runtimeType == other.runtimeType &&
          url == other.url;
}

/// Pre-compiled JavaScript scripts for the Controlled Embed pipeline.
/// Flutter's `ControlledEmbedRunner` feeds these to
/// `WebViewController.runJavaScriptReturningResult` so its DOM-driving
/// behavior matches the headless backend bit-for-bit.
class ExecutionScriptsDto {
  /// JS that writes Input bindings into the DOM. Empty when there is
  /// nothing to write.
  final String write;

  /// JS that fires the Trigger's click. Empty when no Trigger binding
  /// is declared.
  final String trigger;

  /// JS IIFE that returns `JSON.stringify({field: value, …})`. The
  /// caller `JSON.parse`s the returned string into a map. Returns
  /// `"{}"` when there are no Output bindings.
  final String read;

  /// `true` when at least one of `write`/`trigger`/`read` is
  /// actionable. Callers can short-circuit on `false`.
  final bool isActionable;

  const ExecutionScriptsDto({
    required this.write,
    required this.trigger,
    required this.read,
    required this.isActionable,
  });

  @override
  int get hashCode =>
      write.hashCode ^ trigger.hashCode ^ read.hashCode ^ isActionable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionScriptsDto &&
          runtimeType == other.runtimeType &&
          write == other.write &&
          trigger == other.trigger &&
          read == other.read &&
          isActionable == other.isActionable;
}

/// Single selector binding row exposed to Dart. `role` selects the
/// pipeline phase (Input/Trigger/Output); `field` names the form input
/// or output (unused for Trigger); `selector` is the CSS-style selector
/// the embed adapter uses against the embed page.
class SelectorBindingDto {
  final BindingRoleDto role;
  final String field;
  final String selector;
  final ControlledEmbedTriggerActionDto triggerAction;
  final BindingWaitDto? wait;

  const SelectorBindingDto({
    required this.role,
    required this.field,
    required this.selector,
    required this.triggerAction,
    this.wait,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      field.hashCode ^
      selector.hashCode ^
      triggerAction.hashCode ^
      wait.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectorBindingDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          field == other.field &&
          selector == other.selector &&
          triggerAction == other.triggerAction &&
          wait == other.wait;
}
