// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast`, `current_host_state_event`, `deep_link_sinks`, `focus_sinks`, `host_sinks`, `host_state_cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Push a fresh `HostStateEvent` to every live subscriber and
/// update the cached snapshot. Internal callers (boot path,
/// service-desired flips) invoke this so the Dart side sees the
/// same state change exactly once. The cache is updated in lock
/// step with the fan-out so a subscriber attaching mid-broadcast
/// sees a consistent view.
Future<void> hostStateBroadcast({required HostStateEvent state}) =>
    RustLib.instance.api.crateApiEventsHostStateBroadcast(state: state);

/// Stream of host state changes. The cached state is sent as the
/// first event (so subscribers don't sit blank while waiting for
/// the next change); subsequent changes flow through
/// [`host_state_broadcast`].
Stream<HostStateEvent> hostStateStream() =>
    RustLib.instance.api.crateApiEventsHostStateStream();

/// Push a focus-loss event to every live subscriber. Native binary
/// builds wire this from `TaoWindowEvent::Focused(false)`; Flutter
/// today drives focus loss through `window_manager.WindowListener`
/// (see `lib/src/platform/popup_auto_hide.dart`) so this entry point
/// is reserved for parity with the native binary surface.
Future<void> focusLossBroadcast() =>
    RustLib.instance.api.crateApiEventsFocusLossBroadcast();

Stream<void> focusLossStream() =>
    RustLib.instance.api.crateApiEventsFocusLossStream();

/// Push a deep-link URL to every live subscriber. The native binary
/// build emits these when a second-instance forward arrives via the
/// platform single-instance protocol. Flutter builds drive deep
/// links through `app_links` directly today — the stream is reserved
/// for D06 parity.
Future<void> deepLinkBroadcast({required String url}) =>
    RustLib.instance.api.crateApiEventsDeepLinkBroadcast(url: url);

Stream<String> deepLinkStream() =>
    RustLib.instance.api.crateApiEventsDeepLinkStream();

@freezed
sealed class HostStateEvent with _$HostStateEvent {
  const HostStateEvent._();

  const factory HostStateEvent.attached({required String endpoint}) =
      HostStateEvent_Attached;
  const factory HostStateEvent.embedded({required String endpoint}) =
      HostStateEvent_Embedded;
  const factory HostStateEvent.noHost() = HostStateEvent_NoHost;
  const factory HostStateEvent.failed({required String reason}) =
      HostStateEvent_Failed;
}
