// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `from`

/// Look up a translation for `key` in the given `locale`.
///
/// Returns the key itself if no translation exists in either the
/// requested locale or English — the same fallback chain that
/// `upeg_pegboard_ui::i18n::t` enforces. The caller treats a key
/// echo as a missing-catalog-entry signal.
String translate({required String key, required LocaleDto locale}) =>
    RustLib.instance.api.crateApiI18NTranslate(key: key, locale: locale);

/// Look up a translation and substitute `{name}` placeholders.
///
/// The `(arg_keys, arg_vals)` parallel arrays are zipped into the
/// pair form `t_args` expects. Parallel `Vec<String>`s are used —
/// rather than `Vec<(String, String)>` — because FRB v2 round-trips
/// the flat shape with less codegen churn.
String translateArgs({
  required String key,
  required LocaleDto locale,
  required List<String> argKeys,
  required List<String> argVals,
}) => RustLib.instance.api.crateApiI18NTranslateArgs(
  key: key,
  locale: locale,
  argKeys: argKeys,
  argVals: argVals,
);

/// Locale discriminator at the FRB boundary.
///
/// Mirrors [`upeg_core::prefs::Locale`] on the Dart side as a `non_opaque`
/// enum so Dart sees `LocaleDto.en` / `LocaleDto.ko` rather than an
/// opaque pointer. Keep the variant set in lock-step with `Locale` —
/// the `From` impl below pins that contract.
enum LocaleDto { en, ko }
