// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'keyboard.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `keyboard_command_dto_from`, `resolves_in_gui`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Resolve a stroke into a [`KeyboardCommandDto`].
///
/// `key` is a Dart-side label (e.g. `"k"`, `"K"`, `"ArrowUp"`,
/// `"Escape"`, `"F1"`). `ctrl/meta/shift/alt` are the modifier states.
/// `scope` defaults to [`KeyboardScopeDto::Board`] when omitted by the
/// caller; `has_tool_focus` gates the per-pin commands (TogglePin,
/// EditPinColor, StartMove, Reorder) that need a focused tool to act on.
/// Board-management commands (NewBoard, RenameBoard, DeleteBoard,
/// OpenToolPicker) are always live now that the surface is modeless.
///
/// Returns `None` when no command applies — Dart treats `None` as
/// "let the event propagate" so default text input behaviour still
/// works inside text fields.
KeyboardCommandDto? keyboardCommandFor({
  required String key,
  required bool ctrl,
  required bool meta,
  required bool shift,
  required bool alt,
  KeyboardScopeDto? scope,
  required bool hasToolFocus,
}) => RustLib.instance.api.crateApiKeyboardKeyboardCommandFor(
  key: key,
  ctrl: ctrl,
  meta: meta,
  shift: shift,
  alt: alt,
  scope: scope,
  hasToolFocus: hasToolFocus,
);

/// `BoardSlot` validator exposed for the Dart side. Used by integration
/// code that mirrors the slot validation in `KeyboardCommand::SwitchBoard`.
bool boardSlotIsValid({required int slot}) =>
    RustLib.instance.api.crateApiKeyboardBoardSlotIsValid(slot: slot);

/// The shared binding catalog (`upeg_core::binding_catalog`) mirrored
/// for Dart. Powers the `?` cheatsheet overlay and the pin context-menu
/// key hints, so the GUI never hand-writes a shortcut table that could
/// drift from the resolver. Display-only commands (`Copy`,
/// `ClearInput`) are included — the cheatsheet teaches them even though
/// [`keyboard_command_for`] never returns them.
List<ScopeBindingsDto> keyboardBindingCatalog() =>
    RustLib.instance.api.crateApiKeyboardKeyboardBindingCatalog();

/// One cheatsheet row: chords + i18n label key (`keys.cmd.*`).
class BindingEntryDto {
  final String labelKey;
  final bool requiresToolFocus;
  final List<CatalogBindingDto> bindings;

  const BindingEntryDto({
    required this.labelKey,
    required this.requiresToolFocus,
    required this.bindings,
  });

  @override
  int get hashCode =>
      labelKey.hashCode ^ requiresToolFocus.hashCode ^ bindings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BindingEntryDto &&
          runtimeType == other.runtimeType &&
          labelKey == other.labelKey &&
          requiresToolFocus == other.requiresToolFocus &&
          bindings == other.bindings;
}

/// A chord plus the command it resolves to — carried so Dart surfaces
/// (pin context menu key hints, tests) can look bindings up by command
/// instead of by label string.
class CatalogBindingDto {
  final CatalogChordDto chord;
  final KeyboardCommandDto command;

  const CatalogBindingDto({required this.chord, required this.command});

  @override
  int get hashCode => chord.hashCode ^ command.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogBindingDto &&
          runtimeType == other.runtimeType &&
          chord == other.chord &&
          command == other.command;
}

/// One displayable chord of a catalog binding.
class CatalogChordDto {
  final ChordModifierDto modifier;
  final CatalogKeyDto key;

  const CatalogChordDto({required this.modifier, required this.key});

  @override
  int get hashCode => modifier.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogChordDto &&
          runtimeType == other.runtimeType &&
          modifier == other.modifier &&
          key == other.key;
}

@freezed
sealed class CatalogKeyDto with _$CatalogKeyDto {
  const CatalogKeyDto._();

  const factory CatalogKeyDto.up() = CatalogKeyDto_Up;
  const factory CatalogKeyDto.down() = CatalogKeyDto_Down;
  const factory CatalogKeyDto.left() = CatalogKeyDto_Left;
  const factory CatalogKeyDto.right() = CatalogKeyDto_Right;
  const factory CatalogKeyDto.enter() = CatalogKeyDto_Enter;
  const factory CatalogKeyDto.esc() = CatalogKeyDto_Esc;
  const factory CatalogKeyDto.tab() = CatalogKeyDto_Tab;
  const factory CatalogKeyDto.backTab() = CatalogKeyDto_BackTab;
  const factory CatalogKeyDto.pageUp() = CatalogKeyDto_PageUp;
  const factory CatalogKeyDto.pageDown() = CatalogKeyDto_PageDown;
  const factory CatalogKeyDto.home() = CatalogKeyDto_Home;
  const factory CatalogKeyDto.end() = CatalogKeyDto_End;
  const factory CatalogKeyDto.backspace() = CatalogKeyDto_Backspace;
  const factory CatalogKeyDto.space() = CatalogKeyDto_Space;
  const factory CatalogKeyDto.char({required String ch}) = CatalogKeyDto_Char;
  const factory CatalogKeyDto.f({required int number}) = CatalogKeyDto_F;
}

/// Mirror of [`upeg_core::ChordModifier`]: `Primary` renders as the
/// platform's command modifier (⌘ / Ctrl), `Control` is literally Ctrl.
enum ChordModifierDto { none, primary, control }

/// Direction enum mirror for nav/move/page/reorder commands.
enum DirectionDto { up, down, left, right }

@freezed
sealed class KeyboardCommandDto with _$KeyboardCommandDto {
  const KeyboardCommandDto._();

  const factory KeyboardCommandDto.move({required DirectionDto direction}) =
      KeyboardCommandDto_Move;
  const factory KeyboardCommandDto.focusNext() = KeyboardCommandDto_FocusNext;
  const factory KeyboardCommandDto.focusPrevious() =
      KeyboardCommandDto_FocusPrevious;
  const factory KeyboardCommandDto.page({required PageDirectionDto direction}) =
      KeyboardCommandDto_Page;
  const factory KeyboardCommandDto.home() = KeyboardCommandDto_Home;
  const factory KeyboardCommandDto.end() = KeyboardCommandDto_End;
  const factory KeyboardCommandDto.open() = KeyboardCommandDto_Open;
  const factory KeyboardCommandDto.run() = KeyboardCommandDto_Run;
  const factory KeyboardCommandDto.search() = KeyboardCommandDto_Search;
  const factory KeyboardCommandDto.close() = KeyboardCommandDto_Close;
  const factory KeyboardCommandDto.quit() = KeyboardCommandDto_Quit;
  const factory KeyboardCommandDto.openSettings() =
      KeyboardCommandDto_OpenSettings;
  const factory KeyboardCommandDto.cycleBoardFilter() =
      KeyboardCommandDto_CycleBoardFilter;
  const factory KeyboardCommandDto.cycleTagFilter() =
      KeyboardCommandDto_CycleTagFilter;
  const factory KeyboardCommandDto.clearBoardFilter() =
      KeyboardCommandDto_ClearBoardFilter;

  /// `slot` is in the closed range `1..=9` per [`BoardSlot`].
  const factory KeyboardCommandDto.switchBoard({required int slot}) =
      KeyboardCommandDto_SwitchBoard;
  const factory KeyboardCommandDto.newBoard() = KeyboardCommandDto_NewBoard;
  const factory KeyboardCommandDto.renameBoard() =
      KeyboardCommandDto_RenameBoard;
  const factory KeyboardCommandDto.deleteBoard() =
      KeyboardCommandDto_DeleteBoard;
  const factory KeyboardCommandDto.openToolPicker() =
      KeyboardCommandDto_OpenToolPicker;
  const factory KeyboardCommandDto.togglePin() = KeyboardCommandDto_TogglePin;
  const factory KeyboardCommandDto.reorder({
    required OrderDirectionDto direction,
  }) = KeyboardCommandDto_Reorder;

  /// Cmd/Ctrl + `[` — move the focused pin one slot earlier.
  /// Inventory row F12. See [`upeg_core::KeyboardCommand::MovePinPrev`].
  const factory KeyboardCommandDto.movePinPrev() =
      KeyboardCommandDto_MovePinPrev;

  /// Cmd/Ctrl + `]` — symmetric counterpart.
  const factory KeyboardCommandDto.movePinNext() =
      KeyboardCommandDto_MovePinNext;
  const factory KeyboardCommandDto.startMove() = KeyboardCommandDto_StartMove;

  /// `e` with a focused pin — enter resize mode for that pin.
  /// See [`upeg_core::KeyboardCommand::StartResize`].
  const factory KeyboardCommandDto.startResize() =
      KeyboardCommandDto_StartResize;

  /// Span delta emitted in the Resize scope; the direction→delta
  /// mapping already happened in the shared resolver, so Dart applies
  /// `cols`/`rows` verbatim and clamps to the legal span range.
  const factory KeyboardCommandDto.resizeBy({
    required int cols,
    required int rows,
  }) = KeyboardCommandDto_ResizeBy;

  /// `0` in the Resize scope — reset the pin to its manifest
  /// footprint (`clear_pin_span`).
  const factory KeyboardCommandDto.resetSpan() = KeyboardCommandDto_ResetSpan;
  const factory KeyboardCommandDto.commit() = KeyboardCommandDto_Commit;
  const factory KeyboardCommandDto.confirm() = KeyboardCommandDto_Confirm;
  const factory KeyboardCommandDto.cancel() = KeyboardCommandDto_Cancel;

  /// `?` in board scope — open the keyboard-cheatsheet overlay that
  /// renders [`keyboard_binding_catalog`].
  const factory KeyboardCommandDto.showCheatsheet() =
      KeyboardCommandDto_ShowCheatsheet;
  const factory KeyboardCommandDto.text({required String ch}) =
      KeyboardCommandDto_Text;
  const factory KeyboardCommandDto.backspace() = KeyboardCommandDto_Backspace;

  /// `c` with a focused pin — open the pin color dialog.
  /// See [`upeg_core::KeyboardCommand::EditPinColor`].
  const factory KeyboardCommandDto.editPinColor() =
      KeyboardCommandDto_EditPinColor;

  /// Ctrl+U — clear the focused text buffer. Never returned by
  /// [`keyboard_command_for`] (Flutter text fields get native editing
  /// shortcuts); exists so the cheatsheet catalog can display the
  /// shared binding.
  const factory KeyboardCommandDto.clearInput() = KeyboardCommandDto_ClearInput;

  /// F2 — copy the current output. Never returned by
  /// [`keyboard_command_for`] (GUI copy is modal-local); exists so the
  /// cheatsheet catalog can display the shared binding.
  const factory KeyboardCommandDto.copy() = KeyboardCommandDto_Copy;
}

/// Dart-mirrored view of [`upeg_core::KeyboardScope`].
enum KeyboardScopeDto {
  board,
  detail,
  form,
  settings,
  boardEditor,
  confirmDelete,
  toolPicker,
  filterBar,
  rightPane,
  moving,
  resize,
}

enum OrderDirectionDto { previous, next }

enum PageDirectionDto { up, down }

/// One cheatsheet section: a keyboard scope, its i18n label key
/// (`keys.scope.*`), and its rows.
class ScopeBindingsDto {
  final KeyboardScopeDto scope;
  final String labelKey;
  final List<BindingEntryDto> entries;

  const ScopeBindingsDto({
    required this.scope,
    required this.labelKey,
    required this.entries,
  });

  @override
  int get hashCode => scope.hashCode ^ labelKey.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScopeBindingsDto &&
          runtimeType == other.runtimeType &&
          scope == other.scope &&
          labelKey == other.labelKey &&
          entries == other.entries;
}
