// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tools.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Persist `result` as the last outcome of `pin_id` / `tool_id` on
/// `board_key`.
/// Both ok and error results are recorded — the store keeps whatever
/// the dispatch produced; presentation policy (e.g. render only ok
/// results inline) stays with the consumer.
void recordLastOutcome({
  required String boardKey,
  required String pinId,
  required String toolId,
  required CanonicalToolResult result,
}) => RustLib.instance.api.crateApiLastOutcomesRecordLastOutcome(
  boardKey: boardKey,
  pinId: pinId,
  toolId: toolId,
  result: result,
);

/// All persisted outcomes for `board_key`, sorted by pin id.
///
/// Best-effort read (mirrors `list_boards`): an unopenable store or a
/// corrupt row yields an empty / shorter list instead of an error —
/// hydration is a cache warm-up, never a boot blocker.
List<LastOutcomeDto> loadLastOutcomes({required String boardKey}) => RustLib
    .instance
    .api
    .crateApiLastOutcomesLoadLastOutcomes(boardKey: boardKey);

/// One persisted outcome for a pinned tool, as returned by
/// [`load_last_outcomes`].
class LastOutcomeDto {
  /// The placement identity, independent from `tool_id`.
  final String pinId;
  final String toolId;

  /// The canonical result as recorded (minus `error.details`, which
  /// the store does not persist).
  final CanonicalToolResult result;

  /// `true` when the store's size cap dropped output entries.
  final bool truncated;

  /// Epoch milliseconds of the recording write (store clock).
  final PlatformInt64 updatedAtMs;

  const LastOutcomeDto({
    required this.pinId,
    required this.toolId,
    required this.result,
    required this.truncated,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      pinId.hashCode ^
      toolId.hashCode ^
      result.hashCode ^
      truncated.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LastOutcomeDto &&
          runtimeType == other.runtimeType &&
          pinId == other.pinId &&
          toolId == other.toolId &&
          result == other.result &&
          truncated == other.truncated &&
          updatedAtMs == other.updatedAtMs;
}
