// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Snapshot of all persisted memos, sorted by `key` for a stable
/// Dart-visible order. Empty after a fresh install or when storage
/// is unavailable (no config root, etc.).
List<MemoEntry> loadMemos() => RustLib.instance.api.crateApiMemosLoadMemos();

/// Replace the persisted memo map with `entries`. Returns
/// `FrbError::Io` if the backing store rejects the write (native:
/// disk error or missing config root; wasm: localStorage quota /
/// disabled).
void saveMemos({required List<MemoEntry> entries}) =>
    RustLib.instance.api.crateApiMemosSaveMemos(entries: entries);

/// One persisted memo: a stable key + body. The wire shape is a
/// flat `Vec<MemoEntry>` so flutter_rust_bridge can emit a concrete
/// Dart class instead of `Map<String, String>` (matches the rest of
/// this crate's typed-DTO style).
class MemoEntry {
  final String key;
  final String body;

  const MemoEntry({required this.key, required this.body});

  @override
  int get hashCode => key.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          body == other.body;
}
