// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tools.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Search over registered Desktop-surface toolbox tools.
///
/// Empty query returns browseable tools rather than an empty list, so the
/// Flutter palette can pin without requiring the user to type first.
List<PaletteHit> searchTools({required String query}) =>
    RustLib.instance.api.crateApiPaletteSearchTools(query: query);

/// One palette match returned by [`search_tools`].
class PaletteHit {
  /// Canonical tool id (`toolkit.tool` form).
  final String id;

  /// User-facing label.
  final String label;

  /// One-line description.
  final String description;

  /// Higher = better match. Heuristic only — not stable across
  /// versions.
  final double score;

  /// PinKind of the source tool — drives the per-row `KindBadge`
  /// (H11). Sealed enum mirror lives in `api::tools::PinKindDto`.
  final PinKindDto pinKind;

  const PaletteHit({
    required this.id,
    required this.label,
    required this.description,
    required this.score,
    required this.pinKind,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      description.hashCode ^
      score.hashCode ^
      pinKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaletteHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          description == other.description &&
          score == other.score &&
          pinKind == other.pinKind;
}
