// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_paused`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Flip the host pause flag and return the resulting state. Wraps
/// `upeg_cli::toggle_paused`. The state is a process-local
/// `AtomicBool` (see `upeg_cli::infrastructure::pause`) — no I/O,
/// so this call is infallible.
PausedStateSnapshotDto togglePaused() =>
    RustLib.instance.api.crateApiPauseTogglePaused();

/// Sealed enum mirror of the host's pause flag — no `String`
/// discriminator crosses the bridge.
enum PausedStateDto { paused, running }

/// Wrapper struct around [`PausedStateDto`]. FRB v2 cannot return a
/// bare non-opaque enum through `Result<T, FrbError>` cleanly (the
/// generated Dart binding requires a struct-shaped success arm), so
/// the snapshot is the typed envelope the bridge sees.
class PausedStateSnapshotDto {
  final PausedStateDto state;

  const PausedStateSnapshotDto({required this.state});

  @override
  int get hashCode => state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PausedStateSnapshotDto &&
          runtimeType == other.runtimeType &&
          state == other.state;
}
