// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'keyboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tools.dart';
import 'tools/file_input_policy.dart';
import 'tools/input_field.dart';

// These functions are ignored because they are not marked as `pub`: `args_preset_error_to_frb`, `effective_span_width`, `is_project_declared_board`, `load_boards_and_layouts`, `mutate_layout`, `pin_color_error_to_frb`, `pin_span_error_to_frb`, `pinned_tools_for_board_in`, `placement_direction`, `placement_dto_from`, `placement_matches_tag`, `placements_for_board_and_tag_in_layouts`, `validated_pin_span`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Best-effort board list: persisted layout if present, else defaults.
///
/// Mirrors the boot-time `load_boards().unwrap_or_else(default_boards)`
/// pattern from `upeg-pegboard-ui`.
List<BoardDto> listBoards() =>
    RustLib.instance.api.crateApiPegboardListBoards();

/// Fetch the persisted placement list for `board_key`, or the default
/// layout for that board if no saved state exists.
///
/// Unknown `board_key` returns an empty placement list (Dart side decides
/// whether to render a "no such board" view or just an empty canvas).
LayoutSnapshotDto loadLayoutSnapshot({required String boardKey}) =>
    RustLib.instance.api.crateApiPegboardLoadLayoutSnapshot(boardKey: boardKey);

/// Fetch the placement list for `board_key`, optionally narrowed by an
/// effective runtime tag.
///
/// Flutter routes board rendering through this API so Rust remains the single
/// source of truth for tag matching. `None` and `"all"` both mean no tag
/// filter.
LayoutSnapshotDto loadLayoutSnapshotForFilter({
  required String boardKey,
  String? tag,
}) => RustLib.instance.api.crateApiPegboardLoadLayoutSnapshotForFilter(
  boardKey: boardKey,
  tag: tag,
);

PegboardSelectionDto loadPegboardSelection() =>
    RustLib.instance.api.crateApiPegboardLoadPegboardSelection();

void savePegboardSelection({required PegboardSelectionDto selection}) => RustLib
    .instance
    .api
    .crateApiPegboardSavePegboardSelection(selection: selection);

/// Returns the available tag set for the palette / canvas tag chip row.
///
/// The list begins with the `"all"` sentinel followed by every distinct
/// tag carried by any registered tool, sorted lexically. Delegates to
/// `upeg_pegboard_ui::features::layouts::tag_options`, the shared
/// pure-Rust source of truth.
List<String> tagOptions() => RustLib.instance.api.crateApiPegboardTagOptions();

/// Count of tools that carry `tag`. `tag = "all"` returns the total
/// number of registered tools. Mirrors
/// [`upeg_pegboard_ui::features::layouts::count_for_tag`] so the
/// Dart tag chip row can render `"<tag> <n>"` without re-iterating
/// over the toolbox on every rebuild. Returned as `u32` because the
/// FRB wire vocabulary (Dart `int`) is happiest with concrete
/// fixed-size integers and the toolbox count never approaches `u32::MAX`.
int countForTag({required String tag}) =>
    RustLib.instance.api.crateApiPegboardCountForTag(tag: tag);

/// Returns the available tag set for the pins placed on `board_key`.
///
/// `None` means the union of pinned tools across all boards. The list begins
/// with the `"all"` sentinel and then includes tags from the pinned tools only.
List<String> tagOptionsForBoard({String? boardKey}) =>
    RustLib.instance.api.crateApiPegboardTagOptionsForBoard(boardKey: boardKey);

/// Count pins on `board_key` whose tool carries `tag`.
///
/// `tag = "all"` counts every pinned tool for that board. `None` board means
/// the union of pinned tools across all boards.
int countPinnedForTag({String? boardKey, required String tag}) => RustLib
    .instance
    .api
    .crateApiPegboardCountPinnedForTag(boardKey: boardKey, tag: tag);

/// Returns the tools that carry the requested `tag`, sorted by id.
///
/// `tag = "all"` matches every tool. Unknown tags return an empty list.
List<ToolDto> toolsForTag({required String tag}) =>
    RustLib.instance.api.crateApiPegboardToolsForTag(tag: tag);

/// `true` iff `tool_id` already has a placement on `board_key`.
bool isToolPinned({required String boardKey, required String toolId}) => RustLib
    .instance
    .api
    .crateApiPegboardIsToolPinned(boardKey: boardKey, toolId: toolId);

/// List of board keys whose persisted layout already contains `tool_id`.
///
/// Drives the palette's per-board pin chip cluster — each chip's
/// filled/outlined state derives from whether the board key appears in
/// this list. The set is recomputed from the persisted layouts on every
/// call so the Flutter side never holds stale snapshots.
List<String> pinnedBoardsForTool({required String toolId}) =>
    RustLib.instance.api.crateApiPegboardPinnedBoardsForTool(toolId: toolId);

/// Append a placement for `tool_id` at the next free slot on `board_key`,
/// then persist the layouts map. No-op (still `Ok`) if the tool is already
/// pinned. Returns [`FrbError::Validation`] when the board is unknown.
void pinTool({required String boardKey, required String toolId}) => RustLib
    .instance
    .api
    .crateApiPegboardPinTool(boardKey: boardKey, toolId: toolId);

/// Add another instance of a tool to one board and return its stable pin id.
String addPin({required String boardKey, required String toolId}) => RustLib
    .instance
    .api
    .crateApiPegboardAddPin(boardKey: boardKey, toolId: toolId);

/// Remove one instance, leaving any other pins of the same tool in place.
void removePin({required String boardKey, required String pinId}) => RustLib
    .instance
    .api
    .crateApiPegboardRemovePin(boardKey: boardKey, pinId: pinId);

/// Remove every placement carrying `tool_id` from `board_key` and
/// persist. No-op (still `Ok`) if the tool wasn't pinned. Returns
/// [`FrbError::Validation`] when the board is unknown.
void unpinTool({required String boardKey, required String toolId}) => RustLib
    .instance
    .api
    .crateApiPegboardUnpinTool(boardKey: boardKey, toolId: toolId);

/// Swap the selected pin with its row-major neighbour in one persisted layout
/// mutation. This uses the runtime placement swap path rather than composing
/// two push-placement moves, so unrelated pins keep their relative slots.
void reorderPin({
  required String boardKey,
  required String pinId,
  required OrderDirectionDto direction,
}) => RustLib.instance.api.crateApiPegboardReorderPin(
  boardKey: boardKey,
  pinId: pinId,
  direction: direction,
);

void setPinColor({
  required String boardKey,
  required String pinId,
  String? color,
}) => RustLib.instance.api.crateApiPegboardSetPinColor(
  boardKey: boardKey,
  pinId: pinId,
  color: color,
);

/// Set the user span override for `tool_id` on `board_key` and persist.
///
/// `cols` / `rows` are validated through the [`ColSpan`] / [`RowSpan`]
/// newtypes (1..=`BOARD_COLS` columns, ≥1 rows) before any state is
/// touched; failures surface as [`FrbError::Validation`], mirroring
/// [`set_pin_color`]. A tool that isn't pinned on the board is a silent
/// no-op, same as the color path.
///
/// After the span is applied the layout is re-anchored through
/// [`upeg_runtime::pegboard::place_tool_with_push`] at the pin's current
/// cell: growing a pin over a neighbour pushes that neighbour forward in
/// row-major order (exactly what [`preview_resize`] projected) instead
/// of persisting an overlapping layout.
void setPinSpan({
  required String boardKey,
  required String pinId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiPegboardSetPinSpan(
  boardKey: boardKey,
  pinId: pinId,
  cols: cols,
  rows: rows,
);

/// Drop the user span override for `tool_id` on `board_key` so the
/// manifest footprint applies again.
void clearPinSpan({required String boardKey, required String pinId}) => RustLib
    .instance
    .api
    .crateApiPegboardClearPinSpan(boardKey: boardKey, pinId: pinId);

/// Save an argument preset on `tool_id`'s placement on `board_key`.
///
/// `preset_json` must be a JSON object without the reserved
/// execution-context key ([`upeg_core::ArgsPreset`]'s contract);
/// violations surface as [`FrbError::Validation`] before any state is
/// touched.
void setPinArgsPreset({
  required String boardKey,
  required String pinId,
  required String presetJson,
}) => RustLib.instance.api.crateApiPegboardSetPinArgsPreset(
  boardKey: boardKey,
  pinId: pinId,
  presetJson: presetJson,
);

/// Remove the saved argument preset from `tool_id`'s placement on
/// `board_key`.
void clearPinArgsPreset({required String boardKey, required String pinId}) =>
    RustLib.instance.api.crateApiPegboardClearPinArgsPreset(
      boardKey: boardKey,
      pinId: pinId,
    );

/// Create a new board with the given user-supplied `title`. Returns the
/// generated stable `key` (slugified, deduped) so Dart can immediately
/// switch the current-board selection without re-listing.
///
/// Returns [`FrbError::Validation`] when the title is blank or all
/// whitespace, mirroring `add_board`'s `None` contract.
String createBoard({required String title}) =>
    RustLib.instance.api.crateApiPegboardCreateBoard(title: title);

/// Rename `board_key` to `new_title`. Returns [`FrbError::Validation`]
/// when the title is blank or the board doesn't exist.
void renameBoard({required String boardKey, required String newTitle}) =>
    RustLib.instance.api.crateApiPegboardRenameBoard(
      boardKey: boardKey,
      newTitle: newTitle,
    );

/// Delete `board_key` from the persisted boards list and drop its
/// layout entry. Returns [`FrbError::Validation`] when the board
/// doesn't exist, or when the active Project Manifest declares it.
///
/// The project-board refusal is the same rule
/// `upeg_sources::pegboard::remove_board` applies to the TUI: the
/// manifest is a project board's source of truth, so the next load
/// merges it straight back — but the delete would already have swept
/// the board's row, tombstoning every pin on it. Refusing is the honest
/// answer; the delete cannot succeed, only destroy.
void deleteBoard({required String boardKey}) =>
    RustLib.instance.api.crateApiPegboardDeleteBoard(boardKey: boardKey);

/// Commit a pin drag-drop on `board_key`: anchor the dragged tool at
/// `(anchor_x, anchor_y)`, clamp the horizontal anchor inside the fixed
/// six-column grid, and push colliding tools forward in row-major order until
/// the layout is non-overlapping again. Rows grow downward; the board never
/// expands horizontally beyond [`upeg_core::BOARD_COLS`].
///
/// The Dart side computes the drop anchor cell from
/// `(localPosition / cellSize)`, clamping it to the widget's own span,
/// and hands it to this function as `(anchor_x, anchor_y)`; the
/// row-major push/reflow step then runs through
/// `upeg_runtime::pegboard::place_tool_with_push` so it stays canonical
/// across surfaces.
///
/// Returns [`FrbError::Validation`] when the board is unknown, when the anchor
/// is outside the `u16` grid range, when the tool is not registered, or when
/// the manifest span cannot fit within the fixed board width. Positive
/// horizontal anchors beyond [`upeg_core::BOARD_COLS`] are clamped to the last
/// valid start column before the runtime reflow runs.
void movePin({
  required String boardKey,
  required String pinId,
  required int anchorX,
  required int anchorY,
}) => RustLib.instance.api.crateApiPegboardMovePin(
  boardKey: boardKey,
  pinId: pinId,
  anchorX: anchorX,
  anchorY: anchorY,
);

/// Preview the layout that WOULD result if `tool_id` were dropped at
/// `(anchor_x, anchor_y)` on `board_key`, WITHOUT mutating the
/// persisted state. Mirrors [`move_pin`]'s commit semantics through
/// [`upeg_runtime::pegboard::place_tool_with_push`] but runs against a CLONE
/// of the current layout so the read is side-effect-free. Horizontal anchors
/// are clamped/reflowed inside the fixed six columns; rows grow downward.
///
/// Returns an empty `Vec` when the board is unknown, the tool is not
/// pinned on the board, the anchor is outside the `u16` grid range, or
/// the tool is not registered or cannot fit within the fixed board width. The
/// empty result lets the Dart canvas hide the preview overlay without needing
/// a separate "should display" signal.
///
/// Drives F16: the Dart BoardCanvas overlays the returned placements
/// in a ghost layer while move-mode is active, so the user sees the
/// projected push before committing.
List<PlacementDto> previewPush({
  required String boardKey,
  required String pinId,
  required int anchorX,
  required int anchorY,
}) => RustLib.instance.api.crateApiPegboardPreviewPush(
  boardKey: boardKey,
  pinId: pinId,
  anchorX: anchorX,
  anchorY: anchorY,
);

/// Preview the layout that WOULD result if `tool_id`'s span were set to
/// `(cols, rows)` on `board_key`, WITHOUT mutating persisted state.
/// Mirrors [`set_pin_span`]'s commit semantics — apply the span to a
/// CLONE of the current layout, then re-anchor through
/// [`upeg_runtime::pegboard::place_tool_with_push`] at the pin's current
/// cell — so the resize preview and the eventual commit can never
/// disagree.
///
/// Returns an empty `Vec` when the board is unknown, the tool is not
/// pinned on the board, or `(cols, rows)` is outside the legal span
/// range (`ColSpan`/`RowSpan`), matching [`preview_push`]'s "empty means
/// hide the overlay" contract. The Dart canvas compares the returned
/// coordinates against the current layout to decide whether the resize
/// would push neighbours (warn tint) or drop cleanly.
List<PlacementDto> previewResize({
  required String boardKey,
  required String pinId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiPegboardPreviewResize(
  boardKey: boardKey,
  pinId: pinId,
  cols: cols,
  rows: rows,
);

/// Suggest up to three tools to pin on an otherwise empty `board_key`.
///
/// Suggestion policy: tools whose tag list contains the board's slug
/// (case-insensitive) win; if none match we fall back to the first three
/// tools by id. The board key is treated as a tag rather than a keyword
/// search so the Dart side gets stable, deterministic picks.
List<ToolDto> suggestionsForEmptyBoard({required String boardKey}) => RustLib
    .instance
    .api
    .crateApiPegboardSuggestionsForEmptyBoard(boardKey: boardKey);

/// Dart-mirrored view of [`upeg_pegboard_ui::features::boards::Board`].
///
/// `Board` carries `&'static str` fields backed by `Box::leak`ed strings;
/// crossing the FFI boundary requires owned values.
class BoardDto {
  final String key;
  final String title;

  const BoardDto({required this.key, required this.title});

  @override
  int get hashCode => key.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoardDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          title == other.title;
}

/// Snapshot of one board's placements, returned by [`load_layout_snapshot`].
class LayoutSnapshotDto {
  final String boardKey;

  /// Fixed canonical pegboard column count from `upeg_core::BOARD_COLS`.
  /// Flutter uses this six-column width for grid/drop targets; rows grow
  /// downward instead of expanding the board horizontally.
  final int boardCols;
  final List<PlacementDto> placements;

  const LayoutSnapshotDto({
    required this.boardKey,
    required this.boardCols,
    required this.placements,
  });

  @override
  int get hashCode =>
      boardKey.hashCode ^ boardCols.hashCode ^ placements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutSnapshotDto &&
          runtimeType == other.runtimeType &&
          boardKey == other.boardKey &&
          boardCols == other.boardCols &&
          placements == other.placements;
}

class PegboardSelectionDto {
  final String? boardKey;
  final String tag;

  const PegboardSelectionDto({this.boardKey, required this.tag});

  @override
  int get hashCode => boardKey.hashCode ^ tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PegboardSelectionDto &&
          runtimeType == other.runtimeType &&
          boardKey == other.boardKey &&
          tag == other.tag;
}

/// Single pin placement on a board.
///
/// Mirrors [`upeg_core::Placement`] (with the effective size widened to
/// `(w, h)` for Dart layout convenience). `x`/`y` carry the raw
/// pegboard coordinates the Dart canvas uses for absolute-position layout
/// (drag & drop).
class PlacementDto {
  final String pinId;
  final String toolId;

  /// Pegboard column.
  final int x;

  /// Pegboard row.
  final int y;

  /// Effective width in pegboard cells: the user span override when
  /// set, else the manifest footprint (U1=1, U2=2, U2T=1).
  final int w;

  /// Effective height in pegboard cells: the user span override when
  /// set, else the manifest footprint (U1=1, U2=1, U2T=2).
  final int h;

  /// User-specified border color for the pin (`#RRGGBB`), or `None` to use defaults.
  final String? color;

  /// User span override width in cells; `None` when the manifest
  /// footprint applies. Set together with `span_rows`.
  final int? spanCols;

  /// User span override height in cells; `None` when the manifest
  /// footprint applies. Set together with `span_cols`.
  final int? spanRows;

  /// Canonical JSON object text of the pin's saved argument preset,
  /// or `None` when the pin has no preset.
  final String? argsPresetJson;

  const PlacementDto({
    required this.pinId,
    required this.toolId,
    required this.x,
    required this.y,
    required this.w,
    required this.h,
    this.color,
    this.spanCols,
    this.spanRows,
    this.argsPresetJson,
  });

  @override
  int get hashCode =>
      pinId.hashCode ^
      toolId.hashCode ^
      x.hashCode ^
      y.hashCode ^
      w.hashCode ^
      h.hashCode ^
      color.hashCode ^
      spanCols.hashCode ^
      spanRows.hashCode ^
      argsPresetJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlacementDto &&
          runtimeType == other.runtimeType &&
          pinId == other.pinId &&
          toolId == other.toolId &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h &&
          color == other.color &&
          spanCols == other.spanCols &&
          spanRows == other.spanRows &&
          argsPresetJson == other.argsPresetJson;
}
