// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pin_activation.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Decide how a pin tap on `tool_id` should be handled. Unknown tool
/// ids fall back to `OpenModal` — the modal renders its own
/// "unknown tool" error state, so the activation layer doesn't need to
/// emit a separate validation error.
///
/// `args_json` is reserved for future routing rules (e.g. "Launcher
/// with explicit args_json bypasses required-field check"). Today only
/// the implicit empty-args case dispatches immediately.
PinActivationDto pinActivationFor({
  required String toolId,
  required String argsJson,
}) => RustLib.instance.api.crateApiPinActivationPinActivationFor(
  toolId: toolId,
  argsJson: argsJson,
);

@freezed
sealed class PinActivationDto with _$PinActivationDto {
  const PinActivationDto._();

  /// Dispatch the tool immediately (no modal). `tool_id` is echoed so
  /// the Dart side doesn't need to thread the original argument back
  /// through the activation lookup.
  const factory PinActivationDto.dispatchImmediate({required String toolId}) =
      PinActivationDto_DispatchImmediate;

  /// Open the `ExpandedModalPage` for `tool_id`.
  const factory PinActivationDto.openModal({required String toolId}) =
      PinActivationDto_OpenModal;

  /// Open the dedicated full-screen webview page (`EmbedPage`) for a
  /// Passive Embed pin (`PinKind::Embed`) whose URL is resolvable.
  /// Dart calls `resolve_embed_url` when the page mounts.
  const factory PinActivationDto.openEmbed({required String toolId}) =
      PinActivationDto_OpenEmbed;
}
