// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `project_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Current active project, if the desktop has explicitly opened one.
ProjectDefinitionDto? currentProjectDefinition() =>
    RustLib.instance.api.crateApiProjectCurrentProjectDefinition();

/// Parse and validate a selected project without changing the active project.
ProjectDefinitionDto validateProjectRoot({required String root}) =>
    RustLib.instance.api.crateApiProjectValidateProjectRoot(root: root);

/// Activate a validated project. This does not change the process cwd.
ProjectActivationDto activateProject({required String root}) =>
    RustLib.instance.api.crateApiProjectActivateProject(root: root);

/// Persist one explicit source choice for a duplicate project tool id.
ProjectActivationDto setProjectToolChoice({
  required String root,
  required String toolId,
  required ProjectToolChoiceDto choice,
}) => RustLib.instance.api.crateApiProjectSetProjectToolChoice(
  root: root,
  toolId: toolId,
  choice: choice,
);

/// Return the desktop to the global registry and board scope.
void closeProject() => RustLib.instance.api.crateApiProjectCloseProject();

class ProjectActivationDto {
  final String root;
  final String name;
  final List<String> loadedToolIds;
  final List<String> failed;
  final List<ProjectConflictDto> conflicts;

  const ProjectActivationDto({
    required this.root,
    required this.name,
    required this.loadedToolIds,
    required this.failed,
    required this.conflicts,
  });

  @override
  int get hashCode =>
      root.hashCode ^
      name.hashCode ^
      loadedToolIds.hashCode ^
      failed.hashCode ^
      conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectActivationDto &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          name == other.name &&
          loadedToolIds == other.loadedToolIds &&
          failed == other.failed &&
          conflicts == other.conflicts;
}

class ProjectConflictDto {
  final String toolId;
  final String globalSource;
  final String projectSource;
  final ProjectToolChoiceDto? choice;

  const ProjectConflictDto({
    required this.toolId,
    required this.globalSource,
    required this.projectSource,
    this.choice,
  });

  @override
  int get hashCode =>
      toolId.hashCode ^
      globalSource.hashCode ^
      projectSource.hashCode ^
      choice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectConflictDto &&
          runtimeType == other.runtimeType &&
          toolId == other.toolId &&
          globalSource == other.globalSource &&
          projectSource == other.projectSource &&
          choice == other.choice;
}

class ProjectDefinitionDto {
  final String root;
  final String name;
  final int boardCount;
  final List<ProjectToolkitDto> toolkits;
  final List<ProjectConflictDto> conflicts;

  const ProjectDefinitionDto({
    required this.root,
    required this.name,
    required this.boardCount,
    required this.toolkits,
    required this.conflicts,
  });

  @override
  int get hashCode =>
      root.hashCode ^
      name.hashCode ^
      boardCount.hashCode ^
      toolkits.hashCode ^
      conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectDefinitionDto &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          name == other.name &&
          boardCount == other.boardCount &&
          toolkits == other.toolkits &&
          conflicts == other.conflicts;
}

enum ProjectToolChoiceDto { global, project }

class ProjectToolkitDto {
  final String path;
  final String id;
  final List<String> toolIds;

  const ProjectToolkitDto({
    required this.path,
    required this.id,
    required this.toolIds,
  });

  @override
  int get hashCode => path.hashCode ^ id.hashCode ^ toolIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectToolkitDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          id == other.id &&
          toolIds == other.toolIds;
}
