// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// Inspect an External tool without running it. Native only: browser builds
/// have no trustworthy host filesystem or PATH to inspect.
Future<ExternalReadinessDto?> inspectToolReadiness({
  required String toolId,
  String? boardKey,
}) => RustLib.instance.api.crateApiReadinessInspectToolReadiness(
  toolId: toolId,
  boardKey: boardKey,
);

class ExternalReadinessDto {
  final ExternalReadinessStatusDto status;
  final String platform;
  final String? command;
  final String? workingDirectory;
  final String? executable;
  final String? guideUrl;
  final String? instructions;
  final List<String> installCommands;

  const ExternalReadinessDto({
    required this.status,
    required this.platform,
    this.command,
    this.workingDirectory,
    this.executable,
    this.guideUrl,
    this.instructions,
    required this.installCommands,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      platform.hashCode ^
      command.hashCode ^
      workingDirectory.hashCode ^
      executable.hashCode ^
      guideUrl.hashCode ^
      instructions.hashCode ^
      installCommands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalReadinessDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          platform == other.platform &&
          command == other.command &&
          workingDirectory == other.workingDirectory &&
          executable == other.executable &&
          guideUrl == other.guideUrl &&
          instructions == other.instructions &&
          installCommands == other.installCommands;
}

enum ExternalReadinessStatusDto {
  ready,
  missingExecutable,
  missingWorkingDirectory,
  uncheckedCredentialPath,
}
