// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `modified_epoch_millis`, `modified_time`, `pegboard_change_rev`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

SharedStateVersionsDto loadSharedStateVersions() =>
    RustLib.instance.api.crateApiSharedStateLoadSharedStateVersions();

class SharedStateVersionsDto {
  final BigInt? tweaks;
  final BigInt? pegboard;

  const SharedStateVersionsDto({this.tweaks, this.pegboard});

  @override
  int get hashCode => tweaks.hashCode ^ pegboard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedStateVersionsDto &&
          runtimeType == other.runtimeType &&
          tweaks == other.tweaks &&
          pegboard == other.pegboard;
}
