// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pause.dart';

// These functions are ignored because they are not marked as `pub`: `from_cli`, `from_host`, `from_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveredHostReachability`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Read a fresh status snapshot. It performs atomic reads, filesystem
/// discovery, and the discovered host's bounded health probe. Safe to
/// call on every 2s status-bar tick.
///
/// Native reads process-local runtime state plus any separately
/// discovered host; Web has no host process, so the wasm implementation
/// returns a local static snapshot below.
StatusSnapshotDto statusSnapshot() =>
    RustLib.instance.api.crateApiStatusStatusSnapshot();

/// Coarse MCP-import load phase of the process this snapshot came
/// from. Drives the status bar's imports chip via an exhaustive Dart
/// switch — the bar must never guess "still loading" from a count.
///
/// The desktop-embedded host registers imports on a background thread
/// AFTER it starts serving, so `Loading` is a real, seconds-long state
/// a user can watch go by (docs/architecture/mcp.md, "desktop 내장
/// host: 비동기 창"). A desktop that only attaches to a separate host
/// imports nothing itself and honestly reports `NotStarted`.
///
/// `Done` deliberately carries no counts: the chip renders
/// [`StatusSnapshotDto::mcp_import_count`], which is the live
/// provenance-registry count — what is registered NOW, not what one
/// load reported.
enum McpImportPhaseDto {
  /// This process never scheduled an import load.
  notStarted,

  /// A load is scheduled or running — imported tools are still on
  /// their way.
  loading,

  /// The load finished.
  done,

  /// Deliberately loaded nothing (this process is itself somebody's
  /// MCP-import upstream child).
  skipped,
}

/// Coarse classification of the host's network reachability surface.
/// Drives the status-bar dot color via an exhaustive Dart switch.
///
/// An active surface may be process-local or a separately discovered
/// reachable host.
enum NetworkReachabilityDto {
  /// Only loopback (127.0.0.1) is bound — the default safe posture.
  loopbackOnly,

  /// The process-local HTTP surface permits a non-loopback bind, or
  /// a separately discovered host exposes a non-loopback endpoint.
  remoteBindAllowed,

  /// No MCP/HTTP interface is currently active.
  offline,
}

/// Typed network-status snapshot for the Flutter status bar.
///
/// `label` is the short human-readable string the bar renders next to
/// the dot. `reachability` drives the dot color via a sealed switch in
/// the widget — never reach into `label` to infer reachability.
class NetworkStatusDto {
  final NetworkReachabilityDto reachability;
  final String label;

  const NetworkStatusDto({required this.reachability, required this.label});

  @override
  int get hashCode => reachability.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkStatusDto &&
          runtimeType == other.runtimeType &&
          reachability == other.reachability &&
          label == other.label;
}

/// Typed envelope read by the Flutter status bar on every tick.
///
/// Every field has a sealed Dart mirror — no `String` discriminator
/// crosses the bridge. The build version comes from
/// `CARGO_PKG_VERSION` at compile time so the binary and the label
/// can never drift.
class StatusSnapshotDto {
  final NetworkStatusDto network;
  final PausedStateDto paused;

  /// Tools this process imported from upstream MCP servers. Only a
  /// long-lived server process imports (see `docs/architecture/mcp.md`),
  /// so an attach-only desktop reports 0.
  final int mcpImportCount;

  /// Whether that count is final. A count of 0 means "none imported"
  /// only when the phase is not
  /// [`McpImportPhaseDto::Loading`] — during the embedded host's
  /// async import window the count is simply not in yet.
  final McpImportPhaseDto mcpImportPhase;
  final String buildVersion;

  const StatusSnapshotDto({
    required this.network,
    required this.paused,
    required this.mcpImportCount,
    required this.mcpImportPhase,
    required this.buildVersion,
  });

  @override
  int get hashCode =>
      network.hashCode ^
      paused.hashCode ^
      mcpImportCount.hashCode ^
      mcpImportPhase.hashCode ^
      buildVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusSnapshotDto &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          paused == other.paused &&
          mcpImportCount == other.mcpImportCount &&
          mcpImportPhase == other.mcpImportPhase &&
          buildVersion == other.buildVersion;
}
