// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tools/file_input_policy.dart';
import 'tools/input_field.dart';
part 'tools.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `dispatch_tool_impl_for_pin`, `error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

PresentationRowsDto resolveToolPresentationRows({
  required String toolId,
  required String outputsJson,
}) => RustLib.instance.api.crateApiToolsResolveToolPresentationRows(
  toolId: toolId,
  outputsJson: outputsJson,
);

ActionBindingResolutionDto resolveToolActionBindings({
  required String toolId,
  required String actionId,
  required String currentInputsJson,
  String? selectedRowJson,
  required String outputsJson,
}) => RustLib.instance.api.crateApiToolsResolveToolActionBindings(
  toolId: toolId,
  actionId: actionId,
  currentInputsJson: currentInputsJson,
  selectedRowJson: selectedRowJson,
  outputsJson: outputsJson,
);

/// All registered toolkits, sorted by `id`. The UI uses this to drive a
/// toolkit selector / nav.
List<ToolkitDto> listToolkits() =>
    RustLib.instance.api.crateApiToolsListToolkits();

/// All registered tools, sorted by `id`. Optional filter by toolkit:
/// `Some("convert")` returns only `convert.*` tools. `None` returns
/// everything.
List<ToolDto> listTools({String? toolkit}) =>
    RustLib.instance.api.crateApiToolsListTools(toolkit: toolkit);

/// Run the named tool with JSON-encoded args.
///
/// `args_json` is parsed via `serde_json::from_str`. A parse failure
/// surfaces as `ok = false` with a structured `error`, never as a panic.
///
/// `board_key` scopes the dispatch to a board: the pin's saved args
/// preset merges as defaults and the board execution context is
/// annotated (shared `upeg_runtime` synthesis layer — same contract as
/// CLI/HTTP/MCP/TUI). `None` dispatches globally with only the
/// `desktop` surface label.
///
/// `approve` lifts a Chain's approval barrier through a typed parameter;
/// caller-supplied JSON cannot grant approval.
CanonicalToolResult dispatchTool({
  required String toolId,
  required String argsJson,
  String? boardKey,
  String? pinId,
  required bool approve,
}) => RustLib.instance.api.crateApiToolsDispatchTool(
  toolId: toolId,
  argsJson: argsJson,
  boardKey: boardKey,
  pinId: pinId,
  approve: approve,
);

/// Run the named tool with JSON-encoded args on FRB's async dispatch path.
Future<CanonicalToolResult> dispatchToolAsync({
  required String toolId,
  required String argsJson,
  String? boardKey,
  String? pinId,
  required bool approve,
}) => RustLib.instance.api.crateApiToolsDispatchToolAsync(
  toolId: toolId,
  argsJson: argsJson,
  boardKey: boardKey,
  pinId: pinId,
  approve: approve,
);

class ActionBindingResolutionDto {
  final String valuesJson;
  final List<String> diagnostics;
  final List<String> unboundRequiredInputs;

  const ActionBindingResolutionDto({
    required this.valuesJson,
    required this.diagnostics,
    required this.unboundRequiredInputs,
  });

  @override
  int get hashCode =>
      valuesJson.hashCode ^
      diagnostics.hashCode ^
      unboundRequiredInputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActionBindingResolutionDto &&
          runtimeType == other.runtimeType &&
          valuesJson == other.valuesJson &&
          diagnostics == other.diagnostics &&
          unboundRequiredInputs == other.unboundRequiredInputs;
}

enum ActionScopeDto { row, result }

enum ActionSuccessDto { refreshOrigin }

enum BindingSourceDto { input, row, output, constant }

@freezed
sealed class CanonicalFileContent with _$CanonicalFileContent {
  const CanonicalFileContent._();

  const factory CanonicalFileContent.bytes({required Uint8List bytes}) =
      CanonicalFileContent_Bytes;
  const factory CanonicalFileContent.directory({
    required List<CanonicalFileValue> entries,
  }) = CanonicalFileContent_Directory;
}

/// Runtime carrier for canonical file outputs.
class CanonicalFileValue {
  final String name;
  final bool isDir;
  final CanonicalFileContent content;
  final String? mime;

  const CanonicalFileValue({
    required this.name,
    required this.isDir,
    required this.content,
    this.mime,
  });

  @override
  int get hashCode =>
      name.hashCode ^ isDir.hashCode ^ content.hashCode ^ mime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanonicalFileValue &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          content == other.content &&
          mime == other.mime;
}

/// One canonical output entry emitted by a tool dispatch.
///
/// Serde derives back the persisted last-outcome cache
/// (`api::last_outcomes`): entries round-trip through the store's
/// `outputs_json` column as a JSON array of this exact shape.
class CanonicalOutputEntry {
  final String id;
  final String? label;
  final String kind;
  final CanonicalOutputValue value;

  const CanonicalOutputEntry({
    required this.id,
    this.label,
    required this.kind,
    required this.value,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ kind.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanonicalOutputEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          value == other.value;
}

@freezed
sealed class CanonicalOutputValue with _$CanonicalOutputValue {
  const CanonicalOutputValue._();

  const factory CanonicalOutputValue.string({required String value}) =
      CanonicalOutputValue_String;
  const factory CanonicalOutputValue.number({required double value}) =
      CanonicalOutputValue_Number;
  const factory CanonicalOutputValue.integer({required PlatformInt64 value}) =
      CanonicalOutputValue_Integer;
  const factory CanonicalOutputValue.boolean({required bool value}) =
      CanonicalOutputValue_Boolean;
  const factory CanonicalOutputValue.options({required String value}) =
      CanonicalOutputValue_Options;
  const factory CanonicalOutputValue.multiOptions({
    required List<String> value,
  }) = CanonicalOutputValue_MultiOptions;
  const factory CanonicalOutputValue.markdown({required String value}) =
      CanonicalOutputValue_Markdown;
  const factory CanonicalOutputValue.json({required String value}) =
      CanonicalOutputValue_Json;
  const factory CanonicalOutputValue.dateTime({required String value}) =
      CanonicalOutputValue_DateTime;
  const factory CanonicalOutputValue.filePath({required String value}) =
      CanonicalOutputValue_FilePath;
  const factory CanonicalOutputValue.url({required String value}) =
      CanonicalOutputValue_Url;
  const factory CanonicalOutputValue.file({required CanonicalFileValue value}) =
      CanonicalOutputValue_File;
  const factory CanonicalOutputValue.embeddedView({required String value}) =
      CanonicalOutputValue_EmbeddedView;
}

/// Structured failure details emitted by a tool dispatch.
class CanonicalToolError {
  final String code;
  final String message;
  final String? details;

  const CanonicalToolError({
    required this.code,
    required this.message,
    this.details,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanonicalToolError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          details == other.details;
}

/// Canonical result of a single tool dispatch crossing the FFI boundary.
///
/// Success carries the runtime [`ToolSuccess`] shape directly: `outputs`
/// are canonical [`OutputValue`] mirrors and `primary_output_id` points to
/// one of their `id`s. Failure carries a structured [`ToolError`]. No field
/// is reconstructed from legacy stdout text.
class CanonicalToolResult {
  final bool ok;
  final String? primaryOutputId;
  final List<CanonicalOutputEntry> outputs;
  final CanonicalToolError? error;

  const CanonicalToolResult({
    required this.ok,
    this.primaryOutputId,
    required this.outputs,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      primaryOutputId.hashCode ^
      outputs.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanonicalToolResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          primaryOutputId == other.primaryOutputId &&
          outputs == other.outputs &&
          error == other.error;
}

/// Sealed enum mirror of [`upeg_core::Invoker`].
enum InvokerDto { function, external_, http, static_, embed, chain, llm, wasm }

/// One typed output field as exposed to Dart.
///
/// `key` is the canonical output name used inside structured content.
/// `label` falls back to `key` when the source output field has no label.
class OutputFieldDto {
  final String key;
  final String label;
  final String? description;
  final OutputFieldType fieldType;

  const OutputFieldDto({
    required this.key,
    required this.label,
    this.description,
    required this.fieldType,
  });

  @override
  int get hashCode =>
      key.hashCode ^ label.hashCode ^ description.hashCode ^ fieldType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputFieldDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          description == other.description &&
          fieldType == other.fieldType;
}

@freezed
sealed class OutputFieldType with _$OutputFieldType {
  const OutputFieldType._();

  const factory OutputFieldType.text() = OutputFieldType_Text;
  const factory OutputFieldType.number() = OutputFieldType_Number;
  const factory OutputFieldType.integer() = OutputFieldType_Integer;
  const factory OutputFieldType.boolean() = OutputFieldType_Boolean;
  const factory OutputFieldType.file() = OutputFieldType_File;
  const factory OutputFieldType.select({required List<String> options}) =
      OutputFieldType_Select;
  const factory OutputFieldType.multiline() = OutputFieldType_Multiline;
  const factory OutputFieldType.multiOptions({required List<String> options}) =
      OutputFieldType_MultiOptions;
  const factory OutputFieldType.json() = OutputFieldType_Json;
  const factory OutputFieldType.dateTime() = OutputFieldType_DateTime;
  const factory OutputFieldType.markdown() = OutputFieldType_Markdown;
  const factory OutputFieldType.filePath() = OutputFieldType_FilePath;
  const factory OutputFieldType.url() = OutputFieldType_Url;
  const factory OutputFieldType.embeddedView({required String url}) =
      OutputFieldType_EmbeddedView;
}

/// Sealed enum mirror of [`upeg_core::PegboardUnits`].
enum PegboardUnitsDto { u1, u2, u2T }

/// Sealed enum mirror of [`upeg_core::PinKind`].
///
/// Lives in the FRB layer (not core) so flutter_rust_bridge emits a
/// proper Dart sealed class instead of a `String` discriminator the
/// pin widget would have to re-parse.
enum PinKindDto {
  inline,
  launcher,
  live,
  action,
  embed,
  controlledEmbed,
  chain,
  llm,
}

class PresentationActionDto {
  final String id;
  final ActionScopeDto scope;
  final String label;
  final String targetTool;
  final ActionSuccessDto? onSuccess;
  final List<PresentationBindingDto> bindings;

  const PresentationActionDto({
    required this.id,
    required this.scope,
    required this.label,
    required this.targetTool,
    this.onSuccess,
    required this.bindings,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      scope.hashCode ^
      label.hashCode ^
      targetTool.hashCode ^
      onSuccess.hashCode ^
      bindings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationActionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          scope == other.scope &&
          label == other.label &&
          targetTool == other.targetTool &&
          onSuccess == other.onSuccess &&
          bindings == other.bindings;
}

class PresentationBindingDto {
  final String target;
  final BindingSourceDto source;
  final String? pointer;
  final String? valueJson;

  const PresentationBindingDto({
    required this.target,
    required this.source,
    this.pointer,
    this.valueJson,
  });

  @override
  int get hashCode =>
      target.hashCode ^ source.hashCode ^ pointer.hashCode ^ valueJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationBindingDto &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          source == other.source &&
          pointer == other.pointer &&
          valueJson == other.valueJson;
}

class PresentationColumnDto {
  final String label;
  final String pointer;

  const PresentationColumnDto({required this.label, required this.pointer});

  @override
  int get hashCode => label.hashCode ^ pointer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationColumnDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          pointer == other.pointer;
}

class PresentationRowDto {
  final String key;
  final String valueJson;
  final List<String> cellsJson;

  const PresentationRowDto({
    required this.key,
    required this.valueJson,
    required this.cellsJson,
  });

  @override
  int get hashCode => key.hashCode ^ valueJson.hashCode ^ cellsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationRowDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          valueJson == other.valueJson &&
          cellsJson == other.cellsJson;
}

class PresentationRowsDto {
  final List<PresentationRowDto> rows;
  final List<String> diagnostics;
  final bool rowActionsEnabled;

  const PresentationRowsDto({
    required this.rows,
    required this.diagnostics,
    required this.rowActionsEnabled,
  });

  @override
  int get hashCode =>
      rows.hashCode ^ diagnostics.hashCode ^ rowActionsEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationRowsDto &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          diagnostics == other.diagnostics &&
          rowActionsEnabled == other.rowActionsEnabled;
}

@freezed
sealed class SourceDto with _$SourceDto {
  const SourceDto._();

  const factory SourceDto.userInput() = SourceDto_UserInput;
  const factory SourceDto.timer({required BigInt intervalMs}) = SourceDto_Timer;
  const factory SourceDto.shortcut({required String keys}) = SourceDto_Shortcut;
  const factory SourceDto.manual() = SourceDto_Manual;
  const factory SourceDto.static_() = SourceDto_Static;
}

/// Dart-mirrored view of [`upeg_core::ToolMeta`].
///
/// `input_fields` is a flattened, owned view of the tool's `input_spec`
/// so the Dart `GenericForm` widget can pattern-match on a closed sealed
/// enum without crossing the FFI boundary again; `output_fields` mirrors
/// the `output_spec` the same way.
///
/// Batch 1 added `pin_kind` / `invoker` / `pegboard_units` so the Dart
/// Pin widget can drive its kind-coloured accent dot, kind badge,
/// invoker label, and multi-unit cell size without crossing the FFI
/// boundary again per pin.
class ToolDto {
  final String id;
  final String toolkit;
  final String label;
  final String description;
  final List<String> tags;
  final List<InputFieldDto> inputFields;

  /// Ordered typed output fields sourced from `output_spec.fields`.
  /// This is the bridge-level schema Flutter needs for compact Pin
  /// summaries and typed result renderers.
  final List<OutputFieldDto> outputFields;

  /// Mirror of [`upeg_core::PinKind`] — drives the kind-coloured
  /// header dot + footer KindBadge on the Dart Pin widget.
  final PinKindDto pinKind;

  /// Mirror of [`upeg_core::Invoker`] — short footer label on the
  /// Dart Pin widget ("function", "external", …).
  final InvokerDto invoker;

  /// Mirror of [`upeg_core::PegboardUnits`] — drives the Dart
  /// `BoardCanvas` cell footprint via `placement.w` / `placement.h`.
  final PegboardUnitsDto pegboardUnits;

  /// Mirror of [`upeg_core::Source`] — Dart uses this to decide which
  /// pins auto-poll (`Timer { interval_ms }`).
  final SourceDto source;

  /// First manifest-declared credential name (TOML `credentials`
  /// list, registered by the loader), so the "provider not
  /// configured" pin body can render the exact
  /// `upeg credential add <name>` command. `None` when the tool
  /// declares no credentials.
  final String? credentialName;

  /// This tool stops at a human-approval barrier: at least one Chain
  /// step declares `requires_approval`.
  ///
  /// Dart reads this *before* dispatching so the confirmation can sit
  /// in front of the run. Dispatching without it is not unsafe — the
  /// gated step refuses with `approval_required` and nothing runs — but
  /// it is a dead end for the person, who has no way to answer from a
  /// failed result. See `upeg_runtime::approval`'s module docs.
  final bool requiresApproval;

  /// Surface labels (`cli`, `tui`, `desktop`, …) whose approval this
  /// tool honors — the manifest's `approval_surfaces` or the default.
  /// Empty when [`ToolDto::requires_approval`] is false.
  ///
  /// Labels rather than a mirrored enum: `_upeg.surface` is already a
  /// label on the wire, so Dart compares its own surface label against
  /// this list and needs no second vocabulary to keep in sync.
  final List<String> approvalSurfaces;
  final ToolEffectDto effect;
  final ToolPresentationDto? presentation;

  const ToolDto({
    required this.id,
    required this.toolkit,
    required this.label,
    required this.description,
    required this.tags,
    required this.inputFields,
    required this.outputFields,
    required this.pinKind,
    required this.invoker,
    required this.pegboardUnits,
    required this.source,
    this.credentialName,
    required this.requiresApproval,
    required this.approvalSurfaces,
    required this.effect,
    this.presentation,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      toolkit.hashCode ^
      label.hashCode ^
      description.hashCode ^
      tags.hashCode ^
      inputFields.hashCode ^
      outputFields.hashCode ^
      pinKind.hashCode ^
      invoker.hashCode ^
      pegboardUnits.hashCode ^
      source.hashCode ^
      credentialName.hashCode ^
      requiresApproval.hashCode ^
      approvalSurfaces.hashCode ^
      effect.hashCode ^
      presentation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          toolkit == other.toolkit &&
          label == other.label &&
          description == other.description &&
          tags == other.tags &&
          inputFields == other.inputFields &&
          outputFields == other.outputFields &&
          pinKind == other.pinKind &&
          invoker == other.invoker &&
          pegboardUnits == other.pegboardUnits &&
          source == other.source &&
          credentialName == other.credentialName &&
          requiresApproval == other.requiresApproval &&
          approvalSurfaces == other.approvalSurfaces &&
          effect == other.effect &&
          presentation == other.presentation;
}

enum ToolEffectDto { read, write, unknown }

class ToolPresentationDto {
  final int version;
  final String? output;
  final String? rows;
  final String? rowKey;
  final List<PresentationColumnDto> columns;
  final List<PresentationActionDto> actions;

  const ToolPresentationDto({
    required this.version,
    this.output,
    this.rows,
    this.rowKey,
    required this.columns,
    required this.actions,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      output.hashCode ^
      rows.hashCode ^
      rowKey.hashCode ^
      columns.hashCode ^
      actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolPresentationDto &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          output == other.output &&
          rows == other.rows &&
          rowKey == other.rowKey &&
          columns == other.columns &&
          actions == other.actions;
}

/// Dart-mirrored view of [`upeg_core::ToolkitMeta`].
///
/// ToolkitMeta in upeg-core only has `id`, `tags`, `description` —
/// no display_label (toolkits are not directly callable; their label
/// is derived from id at the UI layer).
class ToolkitDto {
  final String id;
  final String description;
  final List<String> tags;

  const ToolkitDto({
    required this.id,
    required this.description,
    required this.tags,
  });

  @override
  int get hashCode => id.hashCode ^ description.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolkitDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          tags == other.tags;
}
