// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `accent_to_str`, `locale_to_str`, `parse_accent`, `parse_locale`, `parse_theme`, `theme_to_str`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `try_from`

/// Shipping locale set. Returned to Dart for the Settings dropdown so
/// the value list stays in sync with the Rust catalog parity tests.
List<String> supportedLocales() =>
    RustLib.instance.api.crateApiTweaksSupportedLocales();

/// Shipping theme set.
List<String> supportedThemes() =>
    RustLib.instance.api.crateApiTweaksSupportedThemes();

/// Shipping accent set.
List<String> supportedAccents() =>
    RustLib.instance.api.crateApiTweaksSupportedAccents();

/// Load the persisted tweaks, or the default value if none exist.
TweaksDto loadTweaks() => RustLib.instance.api.crateApiTweaksLoadTweaks();

/// Persist the tweaks. Returns `Validation` if any enum-shaped field
/// carries an unknown variant string.
void saveTweaks({required TweaksDto tweaks}) =>
    RustLib.instance.api.crateApiTweaksSaveTweaks(tweaks: tweaks);

/// Dart-mirrored view of [`Tweaks`].
///
/// Every field is an owned `String` so it crosses the FFI boundary
/// without lifetime acrobatics. The enum-shaped fields (`theme`,
/// `accent`, `locale`) carry the serde-encoded variant name —
/// `LOCALE_VALUES`, `THEME_VALUES`, `ACCENT_VALUES` enumerate the
/// shipping set so Dart can build dropdowns without re-encoding the
/// list.
class TweaksDto {
  final String theme;
  final String accent;
  final bool showHoles;
  final String locale;

  /// Desktop "Local HTTP host" switch. When on, the app embeds an
  /// in-process HTTP host at boot; when off it only attaches to a host
  /// somebody else started. Default off (FR-16 explicit activation).
  final bool localHttpHost;

  const TweaksDto({
    required this.theme,
    required this.accent,
    required this.showHoles,
    required this.locale,
    required this.localHttpHost,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      accent.hashCode ^
      showHoles.hashCode ^
      locale.hashCode ^
      localHttpHost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TweaksDto &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          accent == other.accent &&
          showHoles == other.showHoles &&
          locale == other.locale &&
          localHttpHost == other.localHttpHost;
}
