// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'boot.dart';
import 'embed.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tools.dart';
part 'webview.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Apply the registered output schema without executing page actions. Safe to
/// call synchronously before storing a session's normal or debugger result.
CanonicalToolResult normalizeWebviewResult({
  required String toolId,
  required WebViewExecutionCompletionDto completion,
}) => RustLib.instance.api.crateApiWebviewNormalizeWebviewResult(
  toolId: toolId,
  completion: completion,
);

/// Reserve a new provider generation and retire any previous provider.
/// The backend remains unavailable until its stream sends `Ready`.
BigInt createWebviewProvider() =>
    RustLib.instance.api.crateApiWebviewCreateWebviewProvider();

/// Attach the reserved provider. An old or disposed generation is rejected.
Stream<WebViewExecutionEventDto> webviewExecutionStream({
  required BigInt providerId,
}) => RustLib.instance.api.crateApiWebviewWebviewExecutionStream(
  providerId: providerId,
);

/// Complete only the matching live invocation. Late or duplicate results are
/// discarded, including results from a replaced provider.
bool completeWebviewExecution({
  required BigInt providerId,
  required BigInt requestId,
  required WebViewExecutionCompletionDto completion,
}) => RustLib.instance.api.crateApiWebviewCompleteWebviewExecution(
  providerId: providerId,
  requestId: requestId,
  completion: completion,
);

/// Detach this generation and wake all its waiting callers. Dispose should
/// invoke this before cancelling the Dart stream subscription.
bool unregisterWebviewProvider({required BigInt providerId}) => RustLib
    .instance
    .api
    .crateApiWebviewUnregisterWebviewProvider(providerId: providerId);

@freezed
sealed class WebViewExecutionCompletionDto
    with _$WebViewExecutionCompletionDto {
  const WebViewExecutionCompletionDto._();

  const factory WebViewExecutionCompletionDto.success({
    required List<(String, String)> outputs,
  }) = WebViewExecutionCompletionDto_Success;
  const factory WebViewExecutionCompletionDto.failed({
    required String message,
  }) = WebViewExecutionCompletionDto_Failed;
  const factory WebViewExecutionCompletionDto.cancelled() =
      WebViewExecutionCompletionDto_Cancelled;
  const factory WebViewExecutionCompletionDto.waitTimeout({
    required BindingRoleDto role,
    required String selector,
    required String forSelector,
    required BindingWaitConditionDto condition,
    required BigInt timeoutMs,
  }) = WebViewExecutionCompletionDto_WaitTimeout;
}

@freezed
sealed class WebViewExecutionEventDto with _$WebViewExecutionEventDto {
  const WebViewExecutionEventDto._();

  const factory WebViewExecutionEventDto.ready() =
      WebViewExecutionEventDto_Ready;
  const factory WebViewExecutionEventDto.execute({
    required WebViewExecutionRequestDto request,
  }) = WebViewExecutionEventDto_Execute;
  const factory WebViewExecutionEventDto.cancel({required BigInt requestId}) =
      WebViewExecutionEventDto_Cancel;
}

/// One invocation, already resolved by the Rust dispatcher.
class WebViewExecutionRequestDto {
  final BigInt requestId;
  final String toolId;

  /// Present only when this call came from an actual board placement.
  final String? boardKey;
  final String? pinId;
  final String url;
  final List<SelectorBindingDto> bindings;
  final ControlledEmbedSettingsDto settings;
  final List<(String, String)> inputs;

  const WebViewExecutionRequestDto({
    required this.requestId,
    required this.toolId,
    this.boardKey,
    this.pinId,
    required this.url,
    required this.bindings,
    required this.settings,
    required this.inputs,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      toolId.hashCode ^
      boardKey.hashCode ^
      pinId.hashCode ^
      url.hashCode ^
      bindings.hashCode ^
      settings.hashCode ^
      inputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebViewExecutionRequestDto &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          toolId == other.toolId &&
          boardKey == other.boardKey &&
          pinId == other.pinId &&
          url == other.url &&
          bindings == other.bindings &&
          settings == other.settings &&
          inputs == other.inputs;
}
