/// Drive a Controlled Embed pipeline against a live `WebViewController`.
///
/// Same role on Flutter as `HeadlessControlledEmbedBackend` has on Rust:
/// take a list of `SelectorBindingDto`, an inputs map, and execute the
/// three-phase (write → trigger → read) pipeline. The JavaScript itself
/// is generated by the Rust `selector_pipeline` (exposed via
/// `buildExecutionScripts`) so both surfaces produce bit-identical
/// scripts — one source of truth.
///
/// SoC:
///  * The runner doesn't import `webview_all` directly. It takes
///    `runCommandJs` and `runResultJs` closures instead so widget tests can
///    feed in fakes without spinning up a real webview platform.
///  * Result is the same `CanonicalToolResult` used by normal tool dispatch,
///    so UI surfaces share one output/error presentation model.
library;

import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:upeg/src/rust/api/embed.dart' as frb;
import 'package:upeg/src/rust/api/embed.dart' show SelectorBindingDto;
import 'package:upeg/src/rust/api/tools.dart';
import 'package:upeg/src/rust/canonical_tool_result_view.dart';
import 'package:upeg/src/widgets/controlled_embed/debug.dart';

/// Test seam: a function that runs JavaScript command (write/trigger).
/// Returns void - used for side-effects without expecting a result.
typedef SelectorJavaScriptCommandRunner = Future<void> Function(String script);

/// Test seam: a function that runs JavaScript and returns the result (read).
/// Returns Object? - used for reading values from the page.
typedef SelectorJavaScriptResultRunner =
    Future<Object?> Function(String script);

/// Test seam: builder for the three pipeline scripts. Production
/// wires Rust's `buildExecutionScripts`; widget tests can swap in a
/// pure-Dart stub so they don't depend on the FRB bridge being
/// initialized.
typedef ExecutionScriptsBuilder =
    frb.ExecutionScriptsDto Function({
      required List<SelectorBindingDto> bindings,
      required List<(String, String)> inputs,
    });

typedef BindingWaitScriptBuilder =
    String Function({required SelectorBindingDto binding});

/// Test seam: a function that runs a wait readiness script and returns
/// `true` when all targeted bindings are ready.
typedef SelectorJavaScriptWaitRunner = Future<bool> Function(String script);

/// Default poll interval for binding wait readiness checks. Matches
/// `DEFAULT_CONTROLLED_EMBED_WAIT_POLL_MS` from `upeg-core/src/types.rs`
/// so both surfaces poll at the same cadence.
const kDefaultWaitPollInterval = Duration(milliseconds: 50);

/// Canonical error code for binding wait timeout failures.
const kControlledEmbedWaitTimeoutCode = 'wait-timeout';

@visibleForTesting
ExecutionScriptsBuilder executionScriptsBuilder =
    _defaultExecutionScriptsBuilder;

@visibleForTesting
BindingWaitScriptBuilder bindingWaitScriptBuilder =
    _defaultBindingWaitScriptBuilder;

frb.ExecutionScriptsDto buildControlledEmbedExecutionScripts({
  required List<SelectorBindingDto> bindings,
  required List<(String, String)> inputs,
}) {
  return executionScriptsBuilder(bindings: bindings, inputs: inputs);
}

frb.ExecutionScriptsDto _defaultExecutionScriptsBuilder({
  required List<SelectorBindingDto> bindings,
  required List<(String, String)> inputs,
}) {
  return frb.buildExecutionScripts(bindings: bindings, inputs: inputs);
}

String _defaultBindingWaitScriptBuilder({required SelectorBindingDto binding}) {
  return frb.buildBindingWaitScript(binding: binding);
}

/// Default settle window between Trigger and Output read. Matches
/// `controlled_embed_headless::DEFAULT_SETTLE_MS` so live-webview and
/// headless surfaces wait the same amount.
const Duration kDefaultSettleDuration = Duration(milliseconds: 500);

/// Canonical output kind for ControlledEmbed selector reads. Browser selector
/// payloads arrive as text snapshots, so Flutter mirrors them as string outputs.
const kControlledEmbedStringOutputKind = 'string';

/// Structured error code for WebView execution exceptions.
const kControlledEmbedExecutionErrorCode = 'controlled_embed_execution_failed';

/// Structured error code for malformed read payloads.
const kControlledEmbedReadPayloadErrorCode = 'controlled_embed_read_payload';

/// Message returned when the embedded page returns a null JavaScript result.
/// This indicates the selector bindings or page readiness issue.
const kControlledEmbedNullJavaScriptResultMessage =
    'Embedded page returned no JavaScript result. Check selector bindings or page readiness.';

/// Maximum number of JSON decode layers to strip when parsing WebView results.
const int _jsonDecodeDepthLimit = 2;

/// Maximum length for truncated strings in error messages.
const int _truncateLength = 200;

/// Exception thrown when a binding wait times out with `on_timeout = fail`.
/// Carries structured metadata so callers can render a canonical error message.
class ControlledEmbedWaitTimeoutError implements Exception {
  const ControlledEmbedWaitTimeoutError({
    required this.roleLabel,
    required this.selector,
    String? forSelector,
    required this.condition,
    required this.timeoutMs,
  }) : forSelector = forSelector ?? selector;

  final String roleLabel;
  final String selector;
  final String forSelector;
  final frb.BindingWaitConditionDto condition;
  final int timeoutMs;

  /// Canonical error message matching the Rust TUI/CLI format.
  String toDisplayMessage() {
    final condLabel = condition == frb.BindingWaitConditionDto.exists
        ? 'exist'
        : 'visible';
    return 'wait for $roleLabel element to $condLabel timed out '
        '${forSelector.isNotEmpty ? 'at "$forSelector" after ' : 'after '}'
        '${timeoutMs}ms';
  }

  @override
  String toString() {
    return 'ControlledEmbedWaitTimeoutError: ${toDisplayMessage()}';
  }
}

/// Normalizes platform-specific execution errors to user-friendly messages.
String _normalizeExecutionError(Object error) {
  if (error is ControlledEmbedWaitTimeoutError) {
    return error.toDisplayMessage();
  }
  // Remove backticks and normalize to lowercase for matching
  final normalized = error.toString().replaceAll('`', '').toLowerCase();
  if (normalized.contains('result of javascript execution returned a null')) {
    return kControlledEmbedNullJavaScriptResultMessage;
  }
  return error.toString();
}

class ControlledEmbedRunner {
  const ControlledEmbedRunner({
    this.settleDelay = kDefaultSettleDuration,
    this.waitPollInterval = kDefaultWaitPollInterval,
  });

  /// How long to wait between Trigger and Output read. Page-specific
  /// tuning could become a manifest field; today we use the same
  /// fixed window on both surfaces.
  final Duration settleDelay;

  /// Poll interval for binding wait readiness checks. Matches
  /// `DEFAULT_CONTROLLED_EMBED_WAIT_POLL_MS` from upeg-core.
  final Duration waitPollInterval;

  Future<CanonicalToolResult> execute({
    required SelectorJavaScriptCommandRunner runCommandJs,
    required SelectorJavaScriptResultRunner runResultJs,
    SelectorJavaScriptWaitRunner? runWaitJs,
    required List<SelectorBindingDto> bindings,
    required Map<String, String> inputs,
    void Function(ControlledEmbedDebugEvent)? onEvent,
    void Function(List<ControlledEmbedSelectorProbe>)? onProbes,
    void Function(ControlledEmbedWaitTimeoutError)? onWaitTimeout,
  }) async {
    final observer = _ControlledEmbedExecutionObserver(
      onEvent: onEvent,
      onProbes: onProbes,
    );
    observer.emit(
      phase: ControlledEmbedDebugPhase.setup,
      level: ControlledEmbedDebugLevel.info,
      message: 'Setup: ${bindings.length} bindings, ${inputs.length} inputs',
      details: {'bindingCount': bindings.length, 'inputCount': inputs.length},
    );
    final scripts = buildControlledEmbedExecutionScripts(
      bindings: bindings,
      inputs: inputs.entries.map((e) => (e.key, e.value)).toList(),
    );
    if (!scripts.isActionable) {
      return const CanonicalToolResult(
        ok: true,
        outputs: <CanonicalOutputEntry>[],
      );
    }

    final waitRunner =
        runWaitJs ??
        (runWaitJs = (script) async {
          final raw = await runResultJs(script);
          return raw == true || raw == 'true';
        });
    var activePhase = ControlledEmbedDebugPhase.setup;
    Future<void> waitForBinding(SelectorBindingDto binding) async {
      if (binding.wait == null) return;
      final waitScript = bindingWaitScriptBuilder(binding: binding);
      if (waitScript.isEmpty) return;
      final details = observer.waitDetails(binding);
      observer.emit(
        kind: _ControlledEmbedExecutionObserver.waitEventKind,
        phase: activePhase,
        level: ControlledEmbedDebugLevel.info,
        message: 'Waiting for ${binding.selector}',
        details: details,
      );
      final ready = await _runSingleBindingWait(
        waitRunner: waitRunner,
        waitScript: waitScript,
        binding: binding,
        pollInterval: waitPollInterval,
      );
      observer.emit(
        kind: _ControlledEmbedExecutionObserver.waitEventKind,
        phase: activePhase,
        level: ready
            ? ControlledEmbedDebugLevel.success
            : ControlledEmbedDebugLevel.warning,
        message: ready
            ? 'Binding ready: ${binding.selector}'
            : 'Wait timed out; continuing: ${binding.selector}',
        details: details,
      );
    }

    try {
      await observer.probe(bindings, runResultJs);
      // ── Write phase: per-binding wait then write ──
      activePhase = ControlledEmbedDebugPhase.write;
      final inputBindings = _bindingsByRole(bindings, frb.BindingRoleDto.input);
      for (final binding in inputBindings) {
        final value = inputs[binding.field];
        if (value == null) continue;
        final bindingInputs = [(binding.field, value)];
        final bindingScripts = executionScriptsBuilder(
          bindings: [binding],
          inputs: bindingInputs,
        );
        await waitForBinding(binding);
        if (bindingScripts.write.isNotEmpty) {
          observer.emit(
            phase: activePhase,
            level: ControlledEmbedDebugLevel.info,
            message: 'Writing input: ${binding.field}',
            details: {'field': binding.field, 'selector': binding.selector},
          );
          await runCommandJs(bindingScripts.write);
          observer.emit(
            phase: activePhase,
            level: ControlledEmbedDebugLevel.success,
            message: 'Input written: ${binding.field}',
            details: {'field': binding.field, 'selector': binding.selector},
          );
        }
      }

      // ── Trigger phase: wait then trigger ──
      activePhase = ControlledEmbedDebugPhase.trigger;
      final triggerBindings = _bindingsByRole(
        bindings,
        frb.BindingRoleDto.trigger,
      );
      for (final binding in triggerBindings) {
        await waitForBinding(binding);
      }
      if (scripts.trigger.isNotEmpty) {
        observer.emit(
          phase: activePhase,
          level: ControlledEmbedDebugLevel.info,
          message: 'Triggering action',
        );
        await runCommandJs(scripts.trigger);
        await Future<void>.delayed(settleDelay);
        observer.emit(
          phase: activePhase,
          level: ControlledEmbedDebugLevel.success,
          message: 'Action triggered successfully',
        );
      }

      await observer.probe(bindings, runResultJs);
      // ── Read phase: per-binding wait then read ──
      activePhase = ControlledEmbedDebugPhase.read;
      final outputBindings = _bindingsByRole(
        bindings,
        frb.BindingRoleDto.output,
      );
      for (final binding in outputBindings) {
        await waitForBinding(binding);
      }
      observer.emit(
        phase: activePhase,
        level: ControlledEmbedDebugLevel.info,
        message: 'Reading outputs',
      );
      final raw = await runResultJs(scripts.read);
      final result = _parseReadResult(raw);
      observer.emit(
        phase: activePhase,
        level: result.ok
            ? ControlledEmbedDebugLevel.success
            : ControlledEmbedDebugLevel.error,
        message: result.ok
            ? 'Outputs read successfully'
            : 'Read failed: ${result.errorMessage}',
        details: result.ok
            ? {
                'outputs': result.jsonValues,
                'outputPreview': {
                  for (final entry in result.outputs)
                    entry.id: previewDebugValue(entry.value.displayText),
                },
              }
            : {'code': result.error?.code},
      );
      return result;
    } catch (e) {
      final isWaitTimeout = e is ControlledEmbedWaitTimeoutError;
      if (e is ControlledEmbedWaitTimeoutError) onWaitTimeout?.call(e);
      final code = isWaitTimeout
          ? kControlledEmbedWaitTimeoutCode
          : kControlledEmbedExecutionErrorCode;
      final message = _normalizeExecutionError(e);
      observer.emit(
        phase: activePhase,
        level: ControlledEmbedDebugLevel.error,
        message: message,
        details: {'code': code},
      );
      return _errorResult(code: code, message: message);
    }
  }

  /// Filters bindings to those matching the given role.
  static List<SelectorBindingDto> _bindingsByRole(
    List<SelectorBindingDto> bindings,
    frb.BindingRoleDto role,
  ) {
    return bindings.where((b) => b.role == role).toList();
  }

  /// Runs the optional wait for a **single binding** before its operation.
  ///
  /// Aligned with Rust semantics in `poll_headless_wait`:
  /// - Builds a focused wait script for only this binding.
  /// - `timeout_ms == 0`: single immediate readiness check.
  /// - Non-zero timeout: poll at `waitPollInterval` until deadline.
  /// - After readiness: apply `settle_ms` fixed delay.
  /// - `on_timeout` is applied **independently** for this binding only:
  ///   - `fail`: throws `ControlledEmbedWaitTimeoutError` keyed to this binding.
  ///   - `continue`: silently returns.
  static Future<bool> _runSingleBindingWait({
    required SelectorJavaScriptWaitRunner waitRunner,
    required String waitScript,
    required frb.SelectorBindingDto binding,
    required Duration pollInterval,
  }) async {
    final wait = binding.wait;
    if (wait == null) return true;

    if (waitScript.isEmpty) return true;

    final timeoutMs = wait.timeoutMs;
    final settleMs = wait.settleMs;
    final onTimeout = wait.onTimeout;
    final roleLabel = _bindingRoleLabel(binding);
    final selector = binding.selector;
    final condLabel = wait.condition;
    final selectorForDisplay =
        (wait.forSelector != null && wait.forSelector!.isNotEmpty)
        ? wait.forSelector!
        : selector;

    // Initial immediate check.
    if (await waitRunner(waitScript)) {
      if (settleMs > BigInt.zero) {
        await Future<void>.delayed(Duration(milliseconds: settleMs.toInt()));
      }
      return true;
    }

    // timeout_ms = 0 → single check already done, skip polling.
    if (timeoutMs > BigInt.zero) {
      final deadline = DateTime.now().add(
        Duration(milliseconds: timeoutMs.toInt()),
      );
      while (DateTime.now().isBefore(deadline)) {
        await Future<void>.delayed(
          Duration(milliseconds: pollInterval.inMilliseconds),
        );
        if (DateTime.now().isAfter(deadline)) break;
        if (await waitRunner(waitScript)) {
          if (settleMs > BigInt.zero) {
            await Future<void>.delayed(
              Duration(milliseconds: settleMs.toInt()),
            );
          }
          return true;
        }
      }
    }

    // Timeout reached — apply this binding's own on_timeout policy.
    if (onTimeout == frb.BindingWaitOnTimeoutDto.fail) {
      throw ControlledEmbedWaitTimeoutError(
        roleLabel: roleLabel,
        selector: selector,
        forSelector: selectorForDisplay,
        condition: condLabel,
        timeoutMs: timeoutMs.toInt(),
      );
    }
    // on_timeout = continue → proceed without error.
    return false;
  }

  /// Human-readable label for a binding's role (input/trigger/output).
  static String _bindingRoleLabel(frb.SelectorBindingDto binding) {
    return switch (binding.role) {
      frb.BindingRoleDto.input => 'input',
      frb.BindingRoleDto.trigger => 'trigger',
      frb.BindingRoleDto.output => 'output',
    };
  }

  CanonicalToolResult _parseReadResult(Object? raw) {
    // The read script returns `JSON.stringify({...})`. Different
    // WebView impls expose the return value differently:
    //  * webview_all on most platforms passes back a `String`.
    //  * Some implementations wrap it in another layer of JSON
    //    encoding (the outer string is `"{\"x\":\"y\"}"`).
    // Strip up to two layers of JSON decoding before parsing as an
    // object. Anything else is an error.
    Object? cursor = raw;
    for (var step = 0; step < _jsonDecodeDepthLimit; step++) {
      if (cursor is String) {
        final s = cursor;
        try {
          cursor = jsonDecode(s);
        } catch (_) {
          return _errorResult(
            code: kControlledEmbedReadPayloadErrorCode,
            message: 'webview returned a non-JSON string: ${_truncated(s)}',
          );
        }
      } else {
        break;
      }
    }
    if (cursor is! Map) {
      return _errorResult(
        code: kControlledEmbedReadPayloadErrorCode,
        message:
            'webview returned a non-object payload: ${_truncated(cursor.toString())}',
      );
    }
    final outputs = <CanonicalOutputEntry>[];
    for (final entry in cursor.entries) {
      final id = entry.key.toString();
      outputs.add(
        CanonicalOutputEntry(
          id: id,
          kind: kControlledEmbedStringOutputKind,
          value: CanonicalOutputValue.string(
            value: entry.value?.toString() ?? '',
          ),
        ),
      );
    }
    return CanonicalToolResult(
      ok: true,
      primaryOutputId: outputs.isEmpty ? null : outputs.first.id,
      outputs: outputs,
    );
  }

  static String _truncated(String s) =>
      s.length > _truncateLength ? '${s.substring(0, _truncateLength)}…' : s;

  static CanonicalToolResult _errorResult({
    required String code,
    required String message,
  }) {
    return CanonicalToolResult(
      ok: false,
      outputs: const <CanonicalOutputEntry>[],
      error: CanonicalToolError(code: code, message: message),
    );
  }
}

/// Records observations without owning a second execution pipeline.
class _ControlledEmbedExecutionObserver {
  _ControlledEmbedExecutionObserver({this.onEvent, this.onProbes});

  static const waitEventKind = 'wait';

  final void Function(ControlledEmbedDebugEvent)? onEvent;
  final void Function(List<ControlledEmbedSelectorProbe>)? onProbes;
  final Stopwatch _stopwatch = Stopwatch()..start();
  int _sequence = 0;

  void emit({
    String? kind,
    required ControlledEmbedDebugPhase phase,
    required ControlledEmbedDebugLevel level,
    required String message,
    Map<String, dynamic>? details,
  }) {
    onEvent?.call(
      ControlledEmbedDebugEvent(
        kind: kind ?? phase.name,
        phase: phase,
        level: level,
        message: message,
        details: details,
        elapsedMs: _stopwatch.elapsedMilliseconds,
        sequence: _sequence++,
      ),
    );
  }

  Map<String, dynamic> waitDetails(SelectorBindingDto binding) {
    final wait = binding.wait!;
    return {
      'field': binding.field,
      'selector': binding.selector,
      'forSelector': wait.forSelector ?? binding.selector,
      'condition': wait.condition.name,
      'timeoutMs': wait.timeoutMs.toInt(),
      'settleMs': wait.settleMs.toInt(),
      'onTimeout': wait.onTimeout.name,
    };
  }

  Future<void> probe(
    List<SelectorBindingDto> bindings,
    SelectorJavaScriptResultRunner runResultJs,
  ) async {
    if (onEvent == null && onProbes == null) return;
    emit(
      phase: ControlledEmbedDebugPhase.probe,
      level: ControlledEmbedDebugLevel.info,
      message: 'Running selector probe',
    );
    try {
      final raw = await runResultJs(
        buildControlledEmbedSelectorProbeScript(bindings),
      );
      final probes = parseControlledEmbedSelectorProbes(raw);
      final matchedCount = probes.where((probe) => probe.matched).length;
      emit(
        phase: ControlledEmbedDebugPhase.probe,
        level: ControlledEmbedDebugLevel.success,
        message: 'Selector probe: $matchedCount/${probes.length} matched',
        details: {'totalProbes': probes.length, 'matchedProbes': matchedCount},
      );
      onProbes?.call(probes);
    } catch (error) {
      emit(
        phase: ControlledEmbedDebugPhase.probe,
        level: ControlledEmbedDebugLevel.error,
        message: 'Selector probe failed: $error',
      );
    }
  }
}
