// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `from`

/// File-selection limits exposed to Dart without weakening Core invariants.
class FileInputPolicyDto {
  final int maxCount;
  final List<String> extensions;
  final BigInt? maxFileBytes;
  final BigInt? maxTotalBytes;

  const FileInputPolicyDto({
    required this.maxCount,
    required this.extensions,
    this.maxFileBytes,
    this.maxTotalBytes,
  });

  @override
  int get hashCode =>
      maxCount.hashCode ^
      extensions.hashCode ^
      maxFileBytes.hashCode ^
      maxTotalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInputPolicyDto &&
          runtimeType == other.runtimeType &&
          maxCount == other.maxCount &&
          extensions == other.extensions &&
          maxFileBytes == other.maxFileBytes &&
          maxTotalBytes == other.maxTotalBytes;
}
