// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'file_input_policy.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'input_field.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `choice_options`, `from_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Mirror of [`upeg_core::ChoiceOption`].
///
/// `label` falls back to `value` (same convention as
/// [`InputFieldDto::label`]) so a Dart dropdown/chip renders
/// `option.label` unconditionally; `description` stays optional.
class ChoiceOptionDto {
  final String value;
  final String label;
  final String? description;

  const ChoiceOptionDto({
    required this.value,
    required this.label,
    this.description,
  });

  @override
  int get hashCode => value.hashCode ^ label.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChoiceOptionDto &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          label == other.label &&
          description == other.description;
}

/// Mirror of [`upeg_core::FieldConstraints`].
class FieldConstraintsDto {
  final NumberConstraintsDto? number;
  final StringConstraintsDto? string;

  const FieldConstraintsDto({this.number, this.string});

  @override
  int get hashCode => number.hashCode ^ string.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldConstraintsDto &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          string == other.string;
}

/// One typed input field as exposed to Dart.
///
/// `key` is the canonical input name used as the JSON map key when the
/// Dart form serialises its state for `dispatchTool`. `label` falls back
/// to `key` when the source `InputFieldSpec.label` is `None` so the Dart
/// side never has to deal with `Option<String>` for display strings.
/// `description` stays optional — it is helper text, not a display name,
/// and there is nothing to fall back to.
class InputFieldDto {
  final String key;
  final String label;
  final String? description;
  final InputFieldType fieldType;
  final bool required_;

  /// `None` when the field declares no constraints at all — the same
  /// distinction [`FieldConstraints::is_empty`] draws in core, kept
  /// rather than shipping an all-`null` struct for every plain field.
  final FieldConstraintsDto? constraints;

  const InputFieldDto({
    required this.key,
    required this.label,
    this.description,
    required this.fieldType,
    required this.required_,
    this.constraints,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      description.hashCode ^
      fieldType.hashCode ^
      required_.hashCode ^
      constraints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputFieldDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          description == other.description &&
          fieldType == other.fieldType &&
          required_ == other.required_ &&
          constraints == other.constraints;
}

@freezed
sealed class InputFieldType with _$InputFieldType {
  const InputFieldType._();

  const factory InputFieldType.text() = InputFieldType_Text;
  const factory InputFieldType.number() = InputFieldType_Number;
  const factory InputFieldType.integer() = InputFieldType_Integer;
  const factory InputFieldType.boolean() = InputFieldType_Boolean;
  const factory InputFieldType.file({required FileInputPolicyDto policy}) =
      InputFieldType_File;
  const factory InputFieldType.select({
    required List<ChoiceOptionDto> options,
  }) = InputFieldType_Select;
  const factory InputFieldType.multiline() = InputFieldType_Multiline;
  const factory InputFieldType.multiOptions({
    required List<ChoiceOptionDto> options,
  }) = InputFieldType_MultiOptions;
  const factory InputFieldType.dateTime() = InputFieldType_DateTime;
  const factory InputFieldType.markdown() = InputFieldType_Markdown;
  const factory InputFieldType.filePath() = InputFieldType_FilePath;
  const factory InputFieldType.url() = InputFieldType_Url;
}

/// Mirror of [`upeg_core::NumberConstraints`] — range and seed value for
/// `Number` / `Integer` fields.
class NumberConstraintsDto {
  final double? min;
  final double? max;
  final double? default_;

  const NumberConstraintsDto({this.min, this.max, this.default_});

  @override
  int get hashCode => min.hashCode ^ max.hashCode ^ default_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NumberConstraintsDto &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          default_ == other.default_;
}

/// Mirror of [`upeg_core::StringConstraints`] — pattern, placeholder and
/// seed value for `String` fields.
class StringConstraintsDto {
  final String? regex;
  final String? placeholder;
  final String? default_;

  const StringConstraintsDto({this.regex, this.placeholder, this.default_});

  @override
  int get hashCode => regex.hashCode ^ placeholder.hashCode ^ default_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringConstraintsDto &&
          runtimeType == other.runtimeType &&
          regex == other.regex &&
          placeholder == other.placeholder &&
          default_ == other.default_;
}
