// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `presentation_detail_dto`, `presentation_field_dto`, `presentation_tone_text`, `resolve_rows`, `resolve_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class PresentationActionAvailabilityDto {
  final String id;
  final bool enabled;
  final String? reason;

  const PresentationActionAvailabilityDto({
    required this.id,
    required this.enabled,
    this.reason,
  });

  @override
  int get hashCode => id.hashCode ^ enabled.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationActionAvailabilityDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          enabled == other.enabled &&
          reason == other.reason;
}

class PresentationDetailDto {
  final List<PresentationFieldDto> fields;
  final String? markdown;
  final String? diff;

  const PresentationDetailDto({required this.fields, this.markdown, this.diff});

  @override
  int get hashCode => fields.hashCode ^ markdown.hashCode ^ diff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationDetailDto &&
          runtimeType == other.runtimeType &&
          fields == other.fields &&
          markdown == other.markdown &&
          diff == other.diff;
}

class PresentationFieldDto {
  final String label;
  final String value;
  final String? tone;

  const PresentationFieldDto({
    required this.label,
    required this.value,
    this.tone,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ tone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationFieldDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          tone == other.tone;
}

class PresentationNoticeDto {
  final String text;
  final String severity;

  const PresentationNoticeDto({required this.text, required this.severity});

  @override
  int get hashCode => text.hashCode ^ severity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationNoticeDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          severity == other.severity;
}

class PresentationRowDetailDto {
  final String key;
  final PresentationDetailDto detail;

  const PresentationRowDetailDto({required this.key, required this.detail});

  @override
  int get hashCode => key.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationRowDetailDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          detail == other.detail;
}

class PresentationStatusDto {
  final String label;
  final String tone;

  const PresentationStatusDto({required this.label, required this.tone});

  @override
  int get hashCode => label.hashCode ^ tone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationStatusDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          tone == other.tone;
}

/// Resolved optional display fields. No JSON pointers cross into the UI.
class PresentationViewDto {
  final String? title;
  final String? subtitle;
  final PresentationStatusDto? status;
  final List<PresentationFieldDto> summary;
  final List<PresentationNoticeDto> notices;
  final PresentationDetailDto? detail;
  final List<PresentationRowDetailDto> rowDetails;
  final String? emptyMessage;
  final List<PresentationActionAvailabilityDto> actions;
  final List<String> diagnostics;

  const PresentationViewDto({
    this.title,
    this.subtitle,
    this.status,
    required this.summary,
    required this.notices,
    this.detail,
    required this.rowDetails,
    this.emptyMessage,
    required this.actions,
    required this.diagnostics,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subtitle.hashCode ^
      status.hashCode ^
      summary.hashCode ^
      notices.hashCode ^
      detail.hashCode ^
      rowDetails.hashCode ^
      emptyMessage.hashCode ^
      actions.hashCode ^
      diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationViewDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          status == other.status &&
          summary == other.summary &&
          notices == other.notices &&
          detail == other.detail &&
          rowDetails == other.rowDetails &&
          emptyMessage == other.emptyMessage &&
          actions == other.actions &&
          diagnostics == other.diagnostics;
}
