// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backup.dart';
import 'api/board_details.dart';
import 'api/boot.dart';
import 'api/capability.dart';
import 'api/deep_link.dart';
import 'api/diagnostics.dart';
import 'api/dispatch_stream.dart';
import 'api/embed.dart';
import 'api/events.dart';
import 'api/i18n.dart';
import 'api/keyboard.dart';
import 'api/last_outcomes.dart';
import 'api/memos.dart';
import 'api/palette.dart';
import 'api/pause.dart';
import 'api/pegboard.dart';
import 'api/pin_activation.dart';
import 'api/project.dart';
import 'api/readiness.dart';
import 'api/shared_state.dart';
import 'api/status.dart';
import 'api/tools.dart';
import 'api/tools/file_input_policy.dart';
import 'api/tools/input_field.dart';
import 'api/tweaks.dart';
import 'api/webview.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<DispatchStreamEventDto>
  dco_decode_StreamSink_dispatch_stream_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<HostStateEvent> dco_decode_StreamSink_host_state_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<void> dco_decode_StreamSink_unit_Sse(dynamic raw);

  @protected
  RustStreamSink<WebViewExecutionEventDto>
  dco_decode_StreamSink_web_view_execution_event_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActionBindingResolutionDto dco_decode_action_binding_resolution_dto(
    dynamic raw,
  );

  @protected
  ActionScopeDto dco_decode_action_scope_dto(dynamic raw);

  @protected
  ActionSuccessDto dco_decode_action_success_dto(dynamic raw);

  @protected
  AppInitReport dco_decode_app_init_report(dynamic raw);

  @protected
  BackupImportReportDto dco_decode_backup_import_report_dto(dynamic raw);

  @protected
  BindingEntryDto dco_decode_binding_entry_dto(dynamic raw);

  @protected
  BindingRoleDto dco_decode_binding_role_dto(dynamic raw);

  @protected
  BindingSourceDto dco_decode_binding_source_dto(dynamic raw);

  @protected
  BindingWaitConditionDto dco_decode_binding_wait_condition_dto(dynamic raw);

  @protected
  BindingWaitDto dco_decode_binding_wait_dto(dynamic raw);

  @protected
  BindingWaitOnTimeoutDto dco_decode_binding_wait_on_timeout_dto(dynamic raw);

  @protected
  BoardConnectionPreviewDto dco_decode_board_connection_preview_dto(
    dynamic raw,
  );

  @protected
  BoardConnectionToolDto dco_decode_board_connection_tool_dto(dynamic raw);

  @protected
  BoardDetailsDto dco_decode_board_details_dto(dynamic raw);

  @protected
  BoardDto dco_decode_board_dto(dynamic raw);

  @protected
  BoardToolReadinessDto dco_decode_board_tool_readiness_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActionSuccessDto dco_decode_box_autoadd_action_success_dto(dynamic raw);

  @protected
  BindingWaitDto dco_decode_box_autoadd_binding_wait_dto(dynamic raw);

  @protected
  CanonicalFileValue dco_decode_box_autoadd_canonical_file_value(dynamic raw);

  @protected
  CanonicalToolError dco_decode_box_autoadd_canonical_tool_error(dynamic raw);

  @protected
  CanonicalToolResult dco_decode_box_autoadd_canonical_tool_result(dynamic raw);

  @protected
  ControlledEmbedSettingsDto
  dco_decode_box_autoadd_controlled_embed_settings_dto(dynamic raw);

  @protected
  ControlledEmbedUserAgentDto
  dco_decode_box_autoadd_controlled_embed_user_agent_dto(dynamic raw);

  @protected
  ControlledEmbedViewportDto
  dco_decode_box_autoadd_controlled_embed_viewport_dto(dynamic raw);

  @protected
  DiagnosticReportDto dco_decode_box_autoadd_diagnostic_report_dto(dynamic raw);

  @protected
  EmbedResolutionDto dco_decode_box_autoadd_embed_resolution_dto(dynamic raw);

  @protected
  ExternalReadinessDto dco_decode_box_autoadd_external_readiness_dto(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FieldConstraintsDto dco_decode_box_autoadd_field_constraints_dto(dynamic raw);

  @protected
  FileInputPolicyDto dco_decode_box_autoadd_file_input_policy_dto(dynamic raw);

  @protected
  HostStateEvent dco_decode_box_autoadd_host_state_event(dynamic raw);

  @protected
  KeyboardCommandDto dco_decode_box_autoadd_keyboard_command_dto(dynamic raw);

  @protected
  KeyboardScopeDto dco_decode_box_autoadd_keyboard_scope_dto(dynamic raw);

  @protected
  LaunchIntentDto dco_decode_box_autoadd_launch_intent_dto(dynamic raw);

  @protected
  NumberConstraintsDto dco_decode_box_autoadd_number_constraints_dto(
    dynamic raw,
  );

  @protected
  PegboardSelectionDto dco_decode_box_autoadd_pegboard_selection_dto(
    dynamic raw,
  );

  @protected
  ProjectDefinitionDto dco_decode_box_autoadd_project_definition_dto(
    dynamic raw,
  );

  @protected
  ProjectToolChoiceDto dco_decode_box_autoadd_project_tool_choice_dto(
    dynamic raw,
  );

  @protected
  SelectorBindingDto dco_decode_box_autoadd_selector_binding_dto(dynamic raw);

  @protected
  StringConstraintsDto dco_decode_box_autoadd_string_constraints_dto(
    dynamic raw,
  );

  @protected
  ToolPresentationDto dco_decode_box_autoadd_tool_presentation_dto(dynamic raw);

  @protected
  TweaksDto dco_decode_box_autoadd_tweaks_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WebViewExecutionCompletionDto
  dco_decode_box_autoadd_web_view_execution_completion_dto(dynamic raw);

  @protected
  WebViewExecutionRequestDto
  dco_decode_box_autoadd_web_view_execution_request_dto(dynamic raw);

  @protected
  CanonicalFileContent dco_decode_canonical_file_content(dynamic raw);

  @protected
  CanonicalFileValue dco_decode_canonical_file_value(dynamic raw);

  @protected
  CanonicalOutputEntry dco_decode_canonical_output_entry(dynamic raw);

  @protected
  CanonicalOutputValue dco_decode_canonical_output_value(dynamic raw);

  @protected
  CanonicalToolError dco_decode_canonical_tool_error(dynamic raw);

  @protected
  CanonicalToolResult dco_decode_canonical_tool_result(dynamic raw);

  @protected
  CatalogBindingDto dco_decode_catalog_binding_dto(dynamic raw);

  @protected
  CatalogChordDto dco_decode_catalog_chord_dto(dynamic raw);

  @protected
  CatalogKeyDto dco_decode_catalog_key_dto(dynamic raw);

  @protected
  ChoiceOptionDto dco_decode_choice_option_dto(dynamic raw);

  @protected
  ChordModifierDto dco_decode_chord_modifier_dto(dynamic raw);

  @protected
  ControlledEmbedSettingsDto dco_decode_controlled_embed_settings_dto(
    dynamic raw,
  );

  @protected
  ControlledEmbedTriggerActionDto
  dco_decode_controlled_embed_trigger_action_dto(dynamic raw);

  @protected
  ControlledEmbedUserAgentDto dco_decode_controlled_embed_user_agent_dto(
    dynamic raw,
  );

  @protected
  ControlledEmbedViewportDto dco_decode_controlled_embed_viewport_dto(
    dynamic raw,
  );

  @protected
  ControlledEmbedViewportPresetDto
  dco_decode_controlled_embed_viewport_preset_dto(dynamic raw);

  @protected
  DesktopLaunchDto dco_decode_desktop_launch_dto(dynamic raw);

  @protected
  DiagnosticReportDto dco_decode_diagnostic_report_dto(dynamic raw);

  @protected
  DiagnosticSummaryDto dco_decode_diagnostic_summary_dto(dynamic raw);

  @protected
  DirectionDto dco_decode_direction_dto(dynamic raw);

  @protected
  DispatchCapabilityDto dco_decode_dispatch_capability_dto(dynamic raw);

  @protected
  DispatchStreamEventDto dco_decode_dispatch_stream_event_dto(dynamic raw);

  @protected
  EmbedResolutionDto dco_decode_embed_resolution_dto(dynamic raw);

  @protected
  ExecutionScriptsDto dco_decode_execution_scripts_dto(dynamic raw);

  @protected
  ExternalReadinessDto dco_decode_external_readiness_dto(dynamic raw);

  @protected
  ExternalReadinessStatusDto dco_decode_external_readiness_status_dto(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldConstraintsDto dco_decode_field_constraints_dto(dynamic raw);

  @protected
  FileInputPolicyDto dco_decode_file_input_policy_dto(dynamic raw);

  @protected
  FrbError dco_decode_frb_error(dynamic raw);

  @protected
  HostStateDto dco_decode_host_state_dto(dynamic raw);

  @protected
  HostStateEvent dco_decode_host_state_event(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InputFieldDto dco_decode_input_field_dto(dynamic raw);

  @protected
  InputFieldType dco_decode_input_field_type(dynamic raw);

  @protected
  InvokerDto dco_decode_invoker_dto(dynamic raw);

  @protected
  KeyboardCommandDto dco_decode_keyboard_command_dto(dynamic raw);

  @protected
  KeyboardScopeDto dco_decode_keyboard_scope_dto(dynamic raw);

  @protected
  LastOutcomeDto dco_decode_last_outcome_dto(dynamic raw);

  @protected
  LaunchIntentDto dco_decode_launch_intent_dto(dynamic raw);

  @protected
  LayoutSnapshotDto dco_decode_layout_snapshot_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BindingEntryDto> dco_decode_list_binding_entry_dto(dynamic raw);

  @protected
  List<BoardConnectionToolDto> dco_decode_list_board_connection_tool_dto(
    dynamic raw,
  );

  @protected
  List<BoardDto> dco_decode_list_board_dto(dynamic raw);

  @protected
  List<CanonicalFileValue> dco_decode_list_canonical_file_value(dynamic raw);

  @protected
  List<CanonicalOutputEntry> dco_decode_list_canonical_output_entry(
    dynamic raw,
  );

  @protected
  List<CatalogBindingDto> dco_decode_list_catalog_binding_dto(dynamic raw);

  @protected
  List<ChoiceOptionDto> dco_decode_list_choice_option_dto(dynamic raw);

  @protected
  List<DiagnosticSummaryDto> dco_decode_list_diagnostic_summary_dto(
    dynamic raw,
  );

  @protected
  List<InputFieldDto> dco_decode_list_input_field_dto(dynamic raw);

  @protected
  List<LastOutcomeDto> dco_decode_list_last_outcome_dto(dynamic raw);

  @protected
  List<MemoEntry> dco_decode_list_memo_entry(dynamic raw);

  @protected
  List<OutputFieldDto> dco_decode_list_output_field_dto(dynamic raw);

  @protected
  List<PaletteHit> dco_decode_list_palette_hit(dynamic raw);

  @protected
  List<PlacementDto> dco_decode_list_placement_dto(dynamic raw);

  @protected
  List<PresentationActionDto> dco_decode_list_presentation_action_dto(
    dynamic raw,
  );

  @protected
  List<PresentationBindingDto> dco_decode_list_presentation_binding_dto(
    dynamic raw,
  );

  @protected
  List<PresentationColumnDto> dco_decode_list_presentation_column_dto(
    dynamic raw,
  );

  @protected
  List<PresentationRowDto> dco_decode_list_presentation_row_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectConflictDto> dco_decode_list_project_conflict_dto(dynamic raw);

  @protected
  List<ProjectToolkitDto> dco_decode_list_project_toolkit_dto(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<ScopeBindingsDto> dco_decode_list_scope_bindings_dto(dynamic raw);

  @protected
  List<SelectorBindingDto> dco_decode_list_selector_binding_dto(dynamic raw);

  @protected
  List<ToolDto> dco_decode_list_tool_dto(dynamic raw);

  @protected
  List<ToolkitDto> dco_decode_list_toolkit_dto(dynamic raw);

  @protected
  LocaleDto dco_decode_locale_dto(dynamic raw);

  @protected
  McpImportPhaseDto dco_decode_mcp_import_phase_dto(dynamic raw);

  @protected
  MemoEntry dco_decode_memo_entry(dynamic raw);

  @protected
  NetworkReachabilityDto dco_decode_network_reachability_dto(dynamic raw);

  @protected
  NetworkStatusDto dco_decode_network_status_dto(dynamic raw);

  @protected
  NumberConstraintsDto dco_decode_number_constraints_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ActionSuccessDto? dco_decode_opt_box_autoadd_action_success_dto(dynamic raw);

  @protected
  BindingWaitDto? dco_decode_opt_box_autoadd_binding_wait_dto(dynamic raw);

  @protected
  CanonicalToolError? dco_decode_opt_box_autoadd_canonical_tool_error(
    dynamic raw,
  );

  @protected
  ControlledEmbedUserAgentDto?
  dco_decode_opt_box_autoadd_controlled_embed_user_agent_dto(dynamic raw);

  @protected
  ControlledEmbedViewportDto?
  dco_decode_opt_box_autoadd_controlled_embed_viewport_dto(dynamic raw);

  @protected
  DiagnosticReportDto? dco_decode_opt_box_autoadd_diagnostic_report_dto(
    dynamic raw,
  );

  @protected
  EmbedResolutionDto? dco_decode_opt_box_autoadd_embed_resolution_dto(
    dynamic raw,
  );

  @protected
  ExternalReadinessDto? dco_decode_opt_box_autoadd_external_readiness_dto(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FieldConstraintsDto? dco_decode_opt_box_autoadd_field_constraints_dto(
    dynamic raw,
  );

  @protected
  KeyboardCommandDto? dco_decode_opt_box_autoadd_keyboard_command_dto(
    dynamic raw,
  );

  @protected
  KeyboardScopeDto? dco_decode_opt_box_autoadd_keyboard_scope_dto(dynamic raw);

  @protected
  LaunchIntentDto? dco_decode_opt_box_autoadd_launch_intent_dto(dynamic raw);

  @protected
  NumberConstraintsDto? dco_decode_opt_box_autoadd_number_constraints_dto(
    dynamic raw,
  );

  @protected
  ProjectDefinitionDto? dco_decode_opt_box_autoadd_project_definition_dto(
    dynamic raw,
  );

  @protected
  ProjectToolChoiceDto? dco_decode_opt_box_autoadd_project_tool_choice_dto(
    dynamic raw,
  );

  @protected
  StringConstraintsDto? dco_decode_opt_box_autoadd_string_constraints_dto(
    dynamic raw,
  );

  @protected
  ToolPresentationDto? dco_decode_opt_box_autoadd_tool_presentation_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OrderDirectionDto dco_decode_order_direction_dto(dynamic raw);

  @protected
  OutputFieldDto dco_decode_output_field_dto(dynamic raw);

  @protected
  OutputFieldType dco_decode_output_field_type(dynamic raw);

  @protected
  PageDirectionDto dco_decode_page_direction_dto(dynamic raw);

  @protected
  PaletteHit dco_decode_palette_hit(dynamic raw);

  @protected
  PausedStateDto dco_decode_paused_state_dto(dynamic raw);

  @protected
  PausedStateSnapshotDto dco_decode_paused_state_snapshot_dto(dynamic raw);

  @protected
  PegboardSelectionDto dco_decode_pegboard_selection_dto(dynamic raw);

  @protected
  PegboardUnitsDto dco_decode_pegboard_units_dto(dynamic raw);

  @protected
  PinActivationDto dco_decode_pin_activation_dto(dynamic raw);

  @protected
  PinKindDto dco_decode_pin_kind_dto(dynamic raw);

  @protected
  PlacementDto dco_decode_placement_dto(dynamic raw);

  @protected
  PresentationActionDto dco_decode_presentation_action_dto(dynamic raw);

  @protected
  PresentationBindingDto dco_decode_presentation_binding_dto(dynamic raw);

  @protected
  PresentationColumnDto dco_decode_presentation_column_dto(dynamic raw);

  @protected
  PresentationRowDto dco_decode_presentation_row_dto(dynamic raw);

  @protected
  PresentationRowsDto dco_decode_presentation_rows_dto(dynamic raw);

  @protected
  ProjectActivationDto dco_decode_project_activation_dto(dynamic raw);

  @protected
  ProjectConflictDto dco_decode_project_conflict_dto(dynamic raw);

  @protected
  ProjectDefinitionDto dco_decode_project_definition_dto(dynamic raw);

  @protected
  ProjectToolChoiceDto dco_decode_project_tool_choice_dto(dynamic raw);

  @protected
  ProjectToolkitDto dco_decode_project_toolkit_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ScopeBindingsDto dco_decode_scope_bindings_dto(dynamic raw);

  @protected
  SelectorBindingDto dco_decode_selector_binding_dto(dynamic raw);

  @protected
  SharedStateVersionsDto dco_decode_shared_state_versions_dto(dynamic raw);

  @protected
  SourceDto dco_decode_source_dto(dynamic raw);

  @protected
  StatusSnapshotDto dco_decode_status_snapshot_dto(dynamic raw);

  @protected
  StringConstraintsDto dco_decode_string_constraints_dto(dynamic raw);

  @protected
  ToolDto dco_decode_tool_dto(dynamic raw);

  @protected
  ToolEffectDto dco_decode_tool_effect_dto(dynamic raw);

  @protected
  ToolPresentationDto dco_decode_tool_presentation_dto(dynamic raw);

  @protected
  ToolkitDto dco_decode_toolkit_dto(dynamic raw);

  @protected
  TweaksDto dco_decode_tweaks_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnsupportedReasonDto dco_decode_unsupported_reason_dto(dynamic raw);

  @protected
  WebViewExecutionCompletionDto dco_decode_web_view_execution_completion_dto(
    dynamic raw,
  );

  @protected
  WebViewExecutionEventDto dco_decode_web_view_execution_event_dto(dynamic raw);

  @protected
  WebViewExecutionRequestDto dco_decode_web_view_execution_request_dto(
    dynamic raw,
  );

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DispatchStreamEventDto>
  sse_decode_StreamSink_dispatch_stream_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HostStateEvent> sse_decode_StreamSink_host_state_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<void> sse_decode_StreamSink_unit_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WebViewExecutionEventDto>
  sse_decode_StreamSink_web_view_execution_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionBindingResolutionDto sse_decode_action_binding_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActionScopeDto sse_decode_action_scope_dto(SseDeserializer deserializer);

  @protected
  ActionSuccessDto sse_decode_action_success_dto(SseDeserializer deserializer);

  @protected
  AppInitReport sse_decode_app_init_report(SseDeserializer deserializer);

  @protected
  BackupImportReportDto sse_decode_backup_import_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  BindingEntryDto sse_decode_binding_entry_dto(SseDeserializer deserializer);

  @protected
  BindingRoleDto sse_decode_binding_role_dto(SseDeserializer deserializer);

  @protected
  BindingSourceDto sse_decode_binding_source_dto(SseDeserializer deserializer);

  @protected
  BindingWaitConditionDto sse_decode_binding_wait_condition_dto(
    SseDeserializer deserializer,
  );

  @protected
  BindingWaitDto sse_decode_binding_wait_dto(SseDeserializer deserializer);

  @protected
  BindingWaitOnTimeoutDto sse_decode_binding_wait_on_timeout_dto(
    SseDeserializer deserializer,
  );

  @protected
  BoardConnectionPreviewDto sse_decode_board_connection_preview_dto(
    SseDeserializer deserializer,
  );

  @protected
  BoardConnectionToolDto sse_decode_board_connection_tool_dto(
    SseDeserializer deserializer,
  );

  @protected
  BoardDetailsDto sse_decode_board_details_dto(SseDeserializer deserializer);

  @protected
  BoardDto sse_decode_board_dto(SseDeserializer deserializer);

  @protected
  BoardToolReadinessDto sse_decode_board_tool_readiness_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActionSuccessDto sse_decode_box_autoadd_action_success_dto(
    SseDeserializer deserializer,
  );

  @protected
  BindingWaitDto sse_decode_box_autoadd_binding_wait_dto(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalFileValue sse_decode_box_autoadd_canonical_file_value(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalToolError sse_decode_box_autoadd_canonical_tool_error(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalToolResult sse_decode_box_autoadd_canonical_tool_result(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedSettingsDto
  sse_decode_box_autoadd_controlled_embed_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedUserAgentDto
  sse_decode_box_autoadd_controlled_embed_user_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedViewportDto
  sse_decode_box_autoadd_controlled_embed_viewport_dto(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosticReportDto sse_decode_box_autoadd_diagnostic_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbedResolutionDto sse_decode_box_autoadd_embed_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExternalReadinessDto sse_decode_box_autoadd_external_readiness_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FieldConstraintsDto sse_decode_box_autoadd_field_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileInputPolicyDto sse_decode_box_autoadd_file_input_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  HostStateEvent sse_decode_box_autoadd_host_state_event(
    SseDeserializer deserializer,
  );

  @protected
  KeyboardCommandDto sse_decode_box_autoadd_keyboard_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyboardScopeDto sse_decode_box_autoadd_keyboard_scope_dto(
    SseDeserializer deserializer,
  );

  @protected
  LaunchIntentDto sse_decode_box_autoadd_launch_intent_dto(
    SseDeserializer deserializer,
  );

  @protected
  NumberConstraintsDto sse_decode_box_autoadd_number_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  PegboardSelectionDto sse_decode_box_autoadd_pegboard_selection_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectDefinitionDto sse_decode_box_autoadd_project_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectToolChoiceDto sse_decode_box_autoadd_project_tool_choice_dto(
    SseDeserializer deserializer,
  );

  @protected
  SelectorBindingDto sse_decode_box_autoadd_selector_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  StringConstraintsDto sse_decode_box_autoadd_string_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  ToolPresentationDto sse_decode_box_autoadd_tool_presentation_dto(
    SseDeserializer deserializer,
  );

  @protected
  TweaksDto sse_decode_box_autoadd_tweaks_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WebViewExecutionCompletionDto
  sse_decode_box_autoadd_web_view_execution_completion_dto(
    SseDeserializer deserializer,
  );

  @protected
  WebViewExecutionRequestDto
  sse_decode_box_autoadd_web_view_execution_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalFileContent sse_decode_canonical_file_content(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalFileValue sse_decode_canonical_file_value(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalOutputEntry sse_decode_canonical_output_entry(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalOutputValue sse_decode_canonical_output_value(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalToolError sse_decode_canonical_tool_error(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalToolResult sse_decode_canonical_tool_result(
    SseDeserializer deserializer,
  );

  @protected
  CatalogBindingDto sse_decode_catalog_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  CatalogChordDto sse_decode_catalog_chord_dto(SseDeserializer deserializer);

  @protected
  CatalogKeyDto sse_decode_catalog_key_dto(SseDeserializer deserializer);

  @protected
  ChoiceOptionDto sse_decode_choice_option_dto(SseDeserializer deserializer);

  @protected
  ChordModifierDto sse_decode_chord_modifier_dto(SseDeserializer deserializer);

  @protected
  ControlledEmbedSettingsDto sse_decode_controlled_embed_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedTriggerActionDto
  sse_decode_controlled_embed_trigger_action_dto(SseDeserializer deserializer);

  @protected
  ControlledEmbedUserAgentDto sse_decode_controlled_embed_user_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedViewportDto sse_decode_controlled_embed_viewport_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedViewportPresetDto
  sse_decode_controlled_embed_viewport_preset_dto(SseDeserializer deserializer);

  @protected
  DesktopLaunchDto sse_decode_desktop_launch_dto(SseDeserializer deserializer);

  @protected
  DiagnosticReportDto sse_decode_diagnostic_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosticSummaryDto sse_decode_diagnostic_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  DirectionDto sse_decode_direction_dto(SseDeserializer deserializer);

  @protected
  DispatchCapabilityDto sse_decode_dispatch_capability_dto(
    SseDeserializer deserializer,
  );

  @protected
  DispatchStreamEventDto sse_decode_dispatch_stream_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbedResolutionDto sse_decode_embed_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExecutionScriptsDto sse_decode_execution_scripts_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExternalReadinessDto sse_decode_external_readiness_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExternalReadinessStatusDto sse_decode_external_readiness_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldConstraintsDto sse_decode_field_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileInputPolicyDto sse_decode_file_input_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  FrbError sse_decode_frb_error(SseDeserializer deserializer);

  @protected
  HostStateDto sse_decode_host_state_dto(SseDeserializer deserializer);

  @protected
  HostStateEvent sse_decode_host_state_event(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InputFieldDto sse_decode_input_field_dto(SseDeserializer deserializer);

  @protected
  InputFieldType sse_decode_input_field_type(SseDeserializer deserializer);

  @protected
  InvokerDto sse_decode_invoker_dto(SseDeserializer deserializer);

  @protected
  KeyboardCommandDto sse_decode_keyboard_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyboardScopeDto sse_decode_keyboard_scope_dto(SseDeserializer deserializer);

  @protected
  LastOutcomeDto sse_decode_last_outcome_dto(SseDeserializer deserializer);

  @protected
  LaunchIntentDto sse_decode_launch_intent_dto(SseDeserializer deserializer);

  @protected
  LayoutSnapshotDto sse_decode_layout_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BindingEntryDto> sse_decode_list_binding_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BoardConnectionToolDto> sse_decode_list_board_connection_tool_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BoardDto> sse_decode_list_board_dto(SseDeserializer deserializer);

  @protected
  List<CanonicalFileValue> sse_decode_list_canonical_file_value(
    SseDeserializer deserializer,
  );

  @protected
  List<CanonicalOutputEntry> sse_decode_list_canonical_output_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<CatalogBindingDto> sse_decode_list_catalog_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ChoiceOptionDto> sse_decode_list_choice_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DiagnosticSummaryDto> sse_decode_list_diagnostic_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<InputFieldDto> sse_decode_list_input_field_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LastOutcomeDto> sse_decode_list_last_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MemoEntry> sse_decode_list_memo_entry(SseDeserializer deserializer);

  @protected
  List<OutputFieldDto> sse_decode_list_output_field_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PaletteHit> sse_decode_list_palette_hit(SseDeserializer deserializer);

  @protected
  List<PlacementDto> sse_decode_list_placement_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PresentationActionDto> sse_decode_list_presentation_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PresentationBindingDto> sse_decode_list_presentation_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PresentationColumnDto> sse_decode_list_presentation_column_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PresentationRowDto> sse_decode_list_presentation_row_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectConflictDto> sse_decode_list_project_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectToolkitDto> sse_decode_list_project_toolkit_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<ScopeBindingsDto> sse_decode_list_scope_bindings_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SelectorBindingDto> sse_decode_list_selector_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ToolDto> sse_decode_list_tool_dto(SseDeserializer deserializer);

  @protected
  List<ToolkitDto> sse_decode_list_toolkit_dto(SseDeserializer deserializer);

  @protected
  LocaleDto sse_decode_locale_dto(SseDeserializer deserializer);

  @protected
  McpImportPhaseDto sse_decode_mcp_import_phase_dto(
    SseDeserializer deserializer,
  );

  @protected
  MemoEntry sse_decode_memo_entry(SseDeserializer deserializer);

  @protected
  NetworkReachabilityDto sse_decode_network_reachability_dto(
    SseDeserializer deserializer,
  );

  @protected
  NetworkStatusDto sse_decode_network_status_dto(SseDeserializer deserializer);

  @protected
  NumberConstraintsDto sse_decode_number_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ActionSuccessDto? sse_decode_opt_box_autoadd_action_success_dto(
    SseDeserializer deserializer,
  );

  @protected
  BindingWaitDto? sse_decode_opt_box_autoadd_binding_wait_dto(
    SseDeserializer deserializer,
  );

  @protected
  CanonicalToolError? sse_decode_opt_box_autoadd_canonical_tool_error(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedUserAgentDto?
  sse_decode_opt_box_autoadd_controlled_embed_user_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  ControlledEmbedViewportDto?
  sse_decode_opt_box_autoadd_controlled_embed_viewport_dto(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosticReportDto? sse_decode_opt_box_autoadd_diagnostic_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmbedResolutionDto? sse_decode_opt_box_autoadd_embed_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExternalReadinessDto? sse_decode_opt_box_autoadd_external_readiness_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FieldConstraintsDto? sse_decode_opt_box_autoadd_field_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyboardCommandDto? sse_decode_opt_box_autoadd_keyboard_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyboardScopeDto? sse_decode_opt_box_autoadd_keyboard_scope_dto(
    SseDeserializer deserializer,
  );

  @protected
  LaunchIntentDto? sse_decode_opt_box_autoadd_launch_intent_dto(
    SseDeserializer deserializer,
  );

  @protected
  NumberConstraintsDto? sse_decode_opt_box_autoadd_number_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectDefinitionDto? sse_decode_opt_box_autoadd_project_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectToolChoiceDto? sse_decode_opt_box_autoadd_project_tool_choice_dto(
    SseDeserializer deserializer,
  );

  @protected
  StringConstraintsDto? sse_decode_opt_box_autoadd_string_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  ToolPresentationDto? sse_decode_opt_box_autoadd_tool_presentation_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OrderDirectionDto sse_decode_order_direction_dto(
    SseDeserializer deserializer,
  );

  @protected
  OutputFieldDto sse_decode_output_field_dto(SseDeserializer deserializer);

  @protected
  OutputFieldType sse_decode_output_field_type(SseDeserializer deserializer);

  @protected
  PageDirectionDto sse_decode_page_direction_dto(SseDeserializer deserializer);

  @protected
  PaletteHit sse_decode_palette_hit(SseDeserializer deserializer);

  @protected
  PausedStateDto sse_decode_paused_state_dto(SseDeserializer deserializer);

  @protected
  PausedStateSnapshotDto sse_decode_paused_state_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  PegboardSelectionDto sse_decode_pegboard_selection_dto(
    SseDeserializer deserializer,
  );

  @protected
  PegboardUnitsDto sse_decode_pegboard_units_dto(SseDeserializer deserializer);

  @protected
  PinActivationDto sse_decode_pin_activation_dto(SseDeserializer deserializer);

  @protected
  PinKindDto sse_decode_pin_kind_dto(SseDeserializer deserializer);

  @protected
  PlacementDto sse_decode_placement_dto(SseDeserializer deserializer);

  @protected
  PresentationActionDto sse_decode_presentation_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  PresentationBindingDto sse_decode_presentation_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  PresentationColumnDto sse_decode_presentation_column_dto(
    SseDeserializer deserializer,
  );

  @protected
  PresentationRowDto sse_decode_presentation_row_dto(
    SseDeserializer deserializer,
  );

  @protected
  PresentationRowsDto sse_decode_presentation_rows_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectActivationDto sse_decode_project_activation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectConflictDto sse_decode_project_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectDefinitionDto sse_decode_project_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectToolChoiceDto sse_decode_project_tool_choice_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectToolkitDto sse_decode_project_toolkit_dto(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ScopeBindingsDto sse_decode_scope_bindings_dto(SseDeserializer deserializer);

  @protected
  SelectorBindingDto sse_decode_selector_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  SharedStateVersionsDto sse_decode_shared_state_versions_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceDto sse_decode_source_dto(SseDeserializer deserializer);

  @protected
  StatusSnapshotDto sse_decode_status_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  StringConstraintsDto sse_decode_string_constraints_dto(
    SseDeserializer deserializer,
  );

  @protected
  ToolDto sse_decode_tool_dto(SseDeserializer deserializer);

  @protected
  ToolEffectDto sse_decode_tool_effect_dto(SseDeserializer deserializer);

  @protected
  ToolPresentationDto sse_decode_tool_presentation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ToolkitDto sse_decode_toolkit_dto(SseDeserializer deserializer);

  @protected
  TweaksDto sse_decode_tweaks_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnsupportedReasonDto sse_decode_unsupported_reason_dto(
    SseDeserializer deserializer,
  );

  @protected
  WebViewExecutionCompletionDto sse_decode_web_view_execution_completion_dto(
    SseDeserializer deserializer,
  );

  @protected
  WebViewExecutionEventDto sse_decode_web_view_execution_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  WebViewExecutionRequestDto sse_decode_web_view_execution_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_dispatch_stream_event_dto_Sse(
    RustStreamSink<DispatchStreamEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_host_state_event_Sse(
    RustStreamSink<HostStateEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_unit_Sse(
    RustStreamSink<void> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_web_view_execution_event_dto_Sse(
    RustStreamSink<WebViewExecutionEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_binding_resolution_dto(
    ActionBindingResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_action_scope_dto(
    ActionScopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_action_success_dto(
    ActionSuccessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_init_report(AppInitReport self, SseSerializer serializer);

  @protected
  void sse_encode_backup_import_report_dto(
    BackupImportReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_entry_dto(
    BindingEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_role_dto(
    BindingRoleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_source_dto(
    BindingSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_wait_condition_dto(
    BindingWaitConditionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_wait_dto(
    BindingWaitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binding_wait_on_timeout_dto(
    BindingWaitOnTimeoutDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_board_connection_preview_dto(
    BoardConnectionPreviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_board_connection_tool_dto(
    BoardConnectionToolDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_board_details_dto(
    BoardDetailsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_board_dto(BoardDto self, SseSerializer serializer);

  @protected
  void sse_encode_board_tool_readiness_dto(
    BoardToolReadinessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_action_success_dto(
    ActionSuccessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_binding_wait_dto(
    BindingWaitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_canonical_file_value(
    CanonicalFileValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_canonical_tool_error(
    CanonicalToolError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_canonical_tool_result(
    CanonicalToolResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_controlled_embed_settings_dto(
    ControlledEmbedSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_controlled_embed_user_agent_dto(
    ControlledEmbedUserAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_controlled_embed_viewport_dto(
    ControlledEmbedViewportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_diagnostic_report_dto(
    DiagnosticReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_embed_resolution_dto(
    EmbedResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_external_readiness_dto(
    ExternalReadinessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_field_constraints_dto(
    FieldConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_input_policy_dto(
    FileInputPolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_host_state_event(
    HostStateEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_keyboard_command_dto(
    KeyboardCommandDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_keyboard_scope_dto(
    KeyboardScopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_launch_intent_dto(
    LaunchIntentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_number_constraints_dto(
    NumberConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pegboard_selection_dto(
    PegboardSelectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_definition_dto(
    ProjectDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_tool_choice_dto(
    ProjectToolChoiceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_selector_binding_dto(
    SelectorBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_string_constraints_dto(
    StringConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tool_presentation_dto(
    ToolPresentationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tweaks_dto(
    TweaksDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_view_execution_completion_dto(
    WebViewExecutionCompletionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_web_view_execution_request_dto(
    WebViewExecutionRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_file_content(
    CanonicalFileContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_file_value(
    CanonicalFileValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_output_entry(
    CanonicalOutputEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_output_value(
    CanonicalOutputValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_tool_error(
    CanonicalToolError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_canonical_tool_result(
    CanonicalToolResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_binding_dto(
    CatalogBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_chord_dto(
    CatalogChordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_key_dto(CatalogKeyDto self, SseSerializer serializer);

  @protected
  void sse_encode_choice_option_dto(
    ChoiceOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chord_modifier_dto(
    ChordModifierDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controlled_embed_settings_dto(
    ControlledEmbedSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controlled_embed_trigger_action_dto(
    ControlledEmbedTriggerActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controlled_embed_user_agent_dto(
    ControlledEmbedUserAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controlled_embed_viewport_dto(
    ControlledEmbedViewportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controlled_embed_viewport_preset_dto(
    ControlledEmbedViewportPresetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_desktop_launch_dto(
    DesktopLaunchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostic_report_dto(
    DiagnosticReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostic_summary_dto(
    DiagnosticSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_direction_dto(DirectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_dispatch_capability_dto(
    DispatchCapabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dispatch_stream_event_dto(
    DispatchStreamEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embed_resolution_dto(
    EmbedResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_execution_scripts_dto(
    ExecutionScriptsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_external_readiness_dto(
    ExternalReadinessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_external_readiness_status_dto(
    ExternalReadinessStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_constraints_dto(
    FieldConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_input_policy_dto(
    FileInputPolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_error(FrbError self, SseSerializer serializer);

  @protected
  void sse_encode_host_state_dto(HostStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_host_state_event(
    HostStateEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_input_field_dto(InputFieldDto self, SseSerializer serializer);

  @protected
  void sse_encode_input_field_type(
    InputFieldType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_invoker_dto(InvokerDto self, SseSerializer serializer);

  @protected
  void sse_encode_keyboard_command_dto(
    KeyboardCommandDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_keyboard_scope_dto(
    KeyboardScopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_last_outcome_dto(
    LastOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_launch_intent_dto(
    LaunchIntentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_layout_snapshot_dto(
    LayoutSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_binding_entry_dto(
    List<BindingEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_board_connection_tool_dto(
    List<BoardConnectionToolDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_board_dto(List<BoardDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_canonical_file_value(
    List<CanonicalFileValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_canonical_output_entry(
    List<CanonicalOutputEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_catalog_binding_dto(
    List<CatalogBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_choice_option_dto(
    List<ChoiceOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diagnostic_summary_dto(
    List<DiagnosticSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_input_field_dto(
    List<InputFieldDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_last_outcome_dto(
    List<LastOutcomeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_memo_entry(
    List<MemoEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_output_field_dto(
    List<OutputFieldDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_palette_hit(
    List<PaletteHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_placement_dto(
    List<PlacementDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_presentation_action_dto(
    List<PresentationActionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_presentation_binding_dto(
    List<PresentationBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_presentation_column_dto(
    List<PresentationColumnDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_presentation_row_dto(
    List<PresentationRowDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_conflict_dto(
    List<ProjectConflictDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_toolkit_dto(
    List<ProjectToolkitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scope_bindings_dto(
    List<ScopeBindingsDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_selector_binding_dto(
    List<SelectorBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tool_dto(List<ToolDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_toolkit_dto(
    List<ToolkitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_locale_dto(LocaleDto self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_import_phase_dto(
    McpImportPhaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memo_entry(MemoEntry self, SseSerializer serializer);

  @protected
  void sse_encode_network_reachability_dto(
    NetworkReachabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_status_dto(
    NetworkStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_number_constraints_dto(
    NumberConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_action_success_dto(
    ActionSuccessDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_binding_wait_dto(
    BindingWaitDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_canonical_tool_error(
    CanonicalToolError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_controlled_embed_user_agent_dto(
    ControlledEmbedUserAgentDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_controlled_embed_viewport_dto(
    ControlledEmbedViewportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_diagnostic_report_dto(
    DiagnosticReportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_embed_resolution_dto(
    EmbedResolutionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_external_readiness_dto(
    ExternalReadinessDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_field_constraints_dto(
    FieldConstraintsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_keyboard_command_dto(
    KeyboardCommandDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_keyboard_scope_dto(
    KeyboardScopeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_launch_intent_dto(
    LaunchIntentDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_number_constraints_dto(
    NumberConstraintsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_project_definition_dto(
    ProjectDefinitionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_project_tool_choice_dto(
    ProjectToolChoiceDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_string_constraints_dto(
    StringConstraintsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_tool_presentation_dto(
    ToolPresentationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_order_direction_dto(
    OrderDirectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_field_dto(
    OutputFieldDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_field_type(
    OutputFieldType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_direction_dto(
    PageDirectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_palette_hit(PaletteHit self, SseSerializer serializer);

  @protected
  void sse_encode_paused_state_dto(
    PausedStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paused_state_snapshot_dto(
    PausedStateSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pegboard_selection_dto(
    PegboardSelectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pegboard_units_dto(
    PegboardUnitsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pin_activation_dto(
    PinActivationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pin_kind_dto(PinKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_placement_dto(PlacementDto self, SseSerializer serializer);

  @protected
  void sse_encode_presentation_action_dto(
    PresentationActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_presentation_binding_dto(
    PresentationBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_presentation_column_dto(
    PresentationColumnDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_presentation_row_dto(
    PresentationRowDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_presentation_rows_dto(
    PresentationRowsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_activation_dto(
    ProjectActivationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_conflict_dto(
    ProjectConflictDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_definition_dto(
    ProjectDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_tool_choice_dto(
    ProjectToolChoiceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_toolkit_dto(
    ProjectToolkitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scope_bindings_dto(
    ScopeBindingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selector_binding_dto(
    SelectorBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shared_state_versions_dto(
    SharedStateVersionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_dto(SourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_status_snapshot_dto(
    StatusSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_string_constraints_dto(
    StringConstraintsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tool_dto(ToolDto self, SseSerializer serializer);

  @protected
  void sse_encode_tool_effect_dto(ToolEffectDto self, SseSerializer serializer);

  @protected
  void sse_encode_tool_presentation_dto(
    ToolPresentationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_toolkit_dto(ToolkitDto self, SseSerializer serializer);

  @protected
  void sse_encode_tweaks_dto(TweaksDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unsupported_reason_dto(
    UnsupportedReasonDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_view_execution_completion_dto(
    WebViewExecutionCompletionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_view_execution_event_dto(
    WebViewExecutionEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_view_execution_request_dto(
    WebViewExecutionRequestDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
